In [10]:
# Model1: XGBoost model to predict Electrical Conductance (EC)

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.metrics import r2_score

import optuna  # pip install optuna
# XGBoost (install first if needed: `pip install xgboost`)
import xgboost as xgb

In [11]:
# Load EC training dataset (features + target already joined)

data_path = "../../Datasets_Ours/Final Datasets/ec_training_complete.csv"
full = pd.read_csv(data_path)

print("EC Training dataset shape:", full.shape)
print("Columns:", list(full.columns))
full.head()

EC Training dataset shape: (9319, 24)
Columns: ['latitude', 'longitude', 'month_fitted', 'swir16', 'swir22', 'red', 'NDMI', 'MNDWI', 'pet', 'aet', 'def', 'q', 'ppt', 'soil', 'srad', 'tmax', 'tmin', 'vap', 'vpd', 'ws', 'pdsi', 'esa_lccs_class', 'esa_change_count', 'electrical_conductance']

,latitude,longitude,month_fitted,swir16,swir22,red,NDMI,MNDWI,pet,aet,...,srad,tmax,tmin,vap,vpd,ws,pdsi,esa_lccs_class,esa_change_count,electrical_conductance
0,-34.405833,19.600556,523.701326,13580.000000,10717.000000,9095.500000,0.166424,-0.184320,132.300003,11.900001,...,263.801483,23.480000,12.179999,1.372,0.79,3.48,-2.59,120.0,0.0,1008.0
1,-34.405833,19.600556,540.219951,14055.575913,11745.353685,10390.225258,0.012771,-0.164021,70.400002,67.599998,...,158.596588,17.779999,7.240000,1.004,0.53,3.36,-3.30,120.0,0.0,1237.0
2,-34.405833,19.600556,470.470642,14115.066596,11908.435926,10413.610383,0.010238,-0.173084,163.000000,18.000000,...,323.498383,26.469999,15.740000,1.703,0.93,2.07,-3.49,120.0,0.0,1053.0
3,-34.405833,19.600556,528.790206,11536.500000,9401.000000,8631.000000,0.129337,-0.139379,51.400002,43.700001,...,113.603378,17.420000,8.400000,1.106,0.45,3.50,-1.60,120.0,0.0,1167.0
4,-34.405833,19.600556,538.392487,13263.500000,10589.000000,9197.500000,0.139460,-0.176520,88.200005,58.600002,...,195.097321,19.730000,10.200000,1.231,0.55,3.64,-1.40,120.0,0.0,877.0

In [12]:
# Build feature matrix X and target y for EC

# Columns to exclude from features
exclude_cols = {
    "electrical_conductance",            # target
    "latitude", "longitude",            # spatial identifiers
}

base_feature_cols = [c for c in full.columns if c not in exclude_cols]
X_full = full[base_feature_cols].copy()
y = full["electrical_conductance"]

print("Initial number of features:", len(base_feature_cols))
print("Features:", base_feature_cols)

# 1) Remove multicollinearity: drop one of each highly correlated pair
corr_matrix = X_full.corr().abs()
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))

high_corr_threshold = 0.95
cols_to_drop_mc = [col for col in upper.columns if any(upper[col] > high_corr_threshold)]

X_mc = X_full.drop(columns=cols_to_drop_mc)
feature_cols_mc = list(X_mc.columns)

print(f"Dropped {len(cols_to_drop_mc)} highly correlated features (>|{high_corr_threshold}|)")
print("Remaining features after multicollinearity reduction:", len(feature_cols_mc))

# For downstream cells we will further reduce by feature importance, then set X and feature_cols there.
# For now, expose X_mc and feature_cols_mc
X_reduced_mc = X_mc.copy()
feature_cols_reduced_mc = feature_cols_mc

print("Example remaining feature columns:", feature_cols_reduced_mc[:10])

Initial number of features: 21
Features: ['month_fitted', 'swir16', 'swir22', 'red', 'NDMI', 'MNDWI', 'pet', 'aet', 'def', 'q', 'ppt', 'soil', 'srad', 'tmax', 'tmin', 'vap', 'vpd', 'ws', 'pdsi', 'esa_lccs_class', 'esa_change_count']
Dropped 2 highly correlated features (>|0.95|)
Remaining features after multicollinearity reduction: 19
Example remaining feature columns: ['month_fitted', 'swir16', 'red', 'NDMI', 'MNDWI', 'pet', 'aet', 'def', 'q', 'ppt']

In [13]:
# Feature selection via XGBoost feature importance (on multicollinearity-reduced set)

# Use a reasonably strong but not overfitted model to rank features
fs_model = xgb.XGBRegressor(
    n_estimators=400,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1,
)

fs_model.fit(X_reduced_mc, y)

importances = fs_model.feature_importances_
fi_fs = pd.DataFrame({"feature": feature_cols_reduced_mc, "importance": importances})
fi_fs = fi_fs.sort_values("importance", ascending=False).reset_index(drop=True)
fi_fs["cum_importance"] = fi_fs["importance"].cumsum()

# Keep features that explain up to 90% of total importance, but ensure at least 20 features
importance_cutoff = 0.90
min_features = 20
selected = fi_fs[fi_fs["cum_importance"] <= importance_cutoff]["feature"].tolist()
if len(selected) < min_features:
    selected = fi_fs.head(min_features)["feature"].tolist()

X = X_reduced_mc[selected].copy()
feature_cols = selected

print("Total features after multicollinearity reduction:", len(feature_cols_reduced_mc))
print("Selected features after importance-based selection:", len(feature_cols))
print("Top selected features:", feature_cols[:15])

Total features after multicollinearity reduction: 19
Selected features after importance-based selection: 19
Top selected features: ['soil', 'esa_change_count', 'esa_lccs_class', 'vpd', 'vap', 'MNDWI', 'pdsi', 'ws', 'tmin', 'pet', 'def', 'ppt', 'NDMI', 'swir16', 'red']

In [14]:
# Train XGBoost model and report R² + feature importances

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = xgb.XGBRegressor(
    n_estimators=400,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1,
)

model.fit(X_train, y_train)

# R² scores
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

r2_train = r2_score(y_train, y_train_pred)
r2_test = r2_score(y_test, y_test_pred)

print(f"Train R²: {r2_train:.3f}")
print(f"Test  R²: {r2_test:.3f}")

# Feature importances
importances = model.feature_importances_
fi = pd.DataFrame({"feature": feature_cols, "importance": importances})
fi = fi.sort_values("importance", ascending=False)

print("\nTop 20 most important features for predicting EC:")
print(fi.head(20).to_string(index=False))

fi.head(20)

Train R²: 0.909
Test  R²: 0.702

Top 20 most important features for predicting EC:
         feature  importance
            soil    0.130285
esa_change_count    0.104395
  esa_lccs_class    0.095007
          swir16    0.058077
             vpd    0.057192
            pdsi    0.050276
           MNDWI    0.047941
             vap    0.046837
             red    0.044663
             pet    0.043950
             def    0.043705
             aet    0.039415
            NDMI    0.039384
            tmin    0.037668
              ws    0.037106
            tmax    0.034567
    month_fitted    0.033905
             ppt    0.031155
               q    0.024473

             feature  importance
0               soil    0.130285
1   esa_change_count    0.104395
2     esa_lccs_class    0.095007
13            swir16    0.058077
3                vpd    0.057192
6               pdsi    0.050276
5              MNDWI    0.047941
4                vap    0.046837
14               red    0.044663
9                pet    0.043950
10               def    0.043705
15               aet    0.039415
12              NDMI    0.039384
8               tmin    0.037668
7                 ws    0.037106
16              tmax    0.034567
18      month_fitted    0.033905
11               ppt    0.031155
17                 q    0.024473

In [15]:
# Stratified K-Fold + Optuna hyperparameter tuning for EC model

# Bin the continuous target into quantiles for stratification
n_bins = 10
# qcut can have duplicate bin edges; drop duplicates
y_strat = pd.qcut(y, q=n_bins, labels=False, duplicates='drop')

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

def objective(trial: optuna.trial.Trial) -> float:
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 200, 400),
        "max_depth": trial.suggest_int("max_depth", 3, 5),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.1, log=True),
        "subsample": trial.suggest_float("subsample", 0.5, 0.8),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 0.8),
        "min_child_weight": trial.suggest_float("min_child_weight", 5.0, 20.0),
        "gamma": trial.suggest_float("gamma", 0.5, 5.0),
        "reg_alpha": trial.suggest_float("reg_alpha", 0.0, 1.0),
        "reg_lambda": trial.suggest_float("reg_lambda", 1.0, 5.0),
        "random_state": 42,
        "n_jobs": -1,
    }

    model = xgb.XGBRegressor(**params)

    cv_scores = []
    for train_idx, valid_idx in skf.split(X, y_strat):
        X_tr, X_val = X.iloc[train_idx], X.iloc[valid_idx]
        y_tr, y_val = y.iloc[train_idx], y.iloc[valid_idx]

        model.fit(
            X_tr,
            y_tr,
            eval_set=[(X_val, y_val)],
            verbose=False,
        )
        y_val_pred = model.predict(X_val)
        cv_scores.append(r2_score(y_val, y_val_pred))

    return float(np.mean(cv_scores))

study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=40, show_progress_bar=True)

print("Best CV R²:", study.best_value)
print("Best params:")
for k, v in study.best_params.items():
    print(f"  {k}: {v}")

[I 2026-02-27 04:12:12,250] A new study created in memory with name: no-name-0f797e91-9f52-44b4-86f7-12cf1a623f1e
Best trial: 0. Best value: 0.469217:   2%|▎         | 1/40 [00:01<01:12,  1.85s/it]

[I 2026-02-27 04:12:14,098] Trial 0 finished with value: 0.46921747407455283 and parameters: {'n_estimators': 255, 'max_depth': 3, 'learning_rate': 0.04249053730836662, 'subsample': 0.5742900201906006, 'colsample_bytree': 0.5269269100859562, 'min_child_weight': 7.316503947276077, 'gamma': 4.905531624818095, 'reg_alpha': 0.5962474526940991, 'reg_lambda': 3.805088968536832}. Best is trial 0 with value: 0.46921747407455283.

Best trial: 0. Best value: 0.469217:   5%|▌         | 2/40 [00:03<01:12,  1.92s/it]

[I 2026-02-27 04:12:16,067] Trial 1 finished with value: 0.40829359274035104 and parameters: {'n_estimators': 210, 'max_depth': 4, 'learning_rate': 0.012235692824635064, 'subsample': 0.7445917209986413, 'colsample_bytree': 0.7884597837663909, 'min_child_weight': 7.130546138284976, 'gamma': 3.7702343533755176, 'reg_alpha': 0.7308100049631572, 'reg_lambda': 3.577065408942812}. Best is trial 0 with value: 0.46921747407455283.

Best trial: 2. Best value: 0.587351:   8%|▊         | 3/40 [00:06<01:23,  2.25s/it]

[I 2026-02-27 04:12:18,715] Trial 2 finished with value: 0.587350802537564 and parameters: {'n_estimators': 226, 'max_depth': 5, 'learning_rate': 0.05411570543557253, 'subsample': 0.7960157867296269, 'colsample_bytree': 0.5704170298147501, 'min_child_weight': 17.647185631183795, 'gamma': 3.0875228503233436, 'reg_alpha': 0.9664994712674159, 'reg_lambda': 2.346966691698886}. Best is trial 2 with value: 0.587350802537564.

Best trial: 2. Best value: 0.587351:  10%|█         | 4/40 [00:11<01:55,  3.21s/it]

[I 2026-02-27 04:12:23,393] Trial 3 finished with value: 0.5376546078675731 and parameters: {'n_estimators': 396, 'max_depth': 3, 'learning_rate': 0.058858345084399355, 'subsample': 0.5899164057728433, 'colsample_bytree': 0.7907304726205969, 'min_child_weight': 7.054271374341545, 'gamma': 2.059346983914739, 'reg_alpha': 0.563282482375782, 'reg_lambda': 1.080975633186866}. Best is trial 2 with value: 0.587350802537564.

Best trial: 2. Best value: 0.587351:  12%|█▎        | 5/40 [00:14<01:53,  3.25s/it]

[I 2026-02-27 04:12:26,716] Trial 4 finished with value: 0.42188850680299916 and parameters: {'n_estimators': 342, 'max_depth': 3, 'learning_rate': 0.01570450223024711, 'subsample': 0.572828226219756, 'colsample_bytree': 0.7776753544301676, 'min_child_weight': 6.00045806781279, 'gamma': 2.582640342339944, 'reg_alpha': 0.9189999722188775, 'reg_lambda': 3.5635728236425357}. Best is trial 2 with value: 0.587350802537564.

Best trial: 2. Best value: 0.587351:  15%|█▌        | 6/40 [00:16<01:37,  2.87s/it]

[I 2026-02-27 04:12:28,861] Trial 5 finished with value: 0.4712435233064872 and parameters: {'n_estimators': 216, 'max_depth': 3, 'learning_rate': 0.050481788249557666, 'subsample': 0.6499267373701836, 'colsample_bytree': 0.5716041302511717, 'min_child_weight': 6.318235199873259, 'gamma': 1.307976242410956, 'reg_alpha': 0.5739404376364243, 'reg_lambda': 1.9831965966989324}. Best is trial 2 with value: 0.587350802537564.

Best trial: 6. Best value: 0.593866:  18%|█▊        | 7/40 [00:21<01:54,  3.47s/it]

[I 2026-02-27 04:12:33,543] Trial 6 finished with value: 0.5938659587616151 and parameters: {'n_estimators': 371, 'max_depth': 4, 'learning_rate': 0.06856740026981016, 'subsample': 0.7054586042310929, 'colsample_bytree': 0.6609237993768158, 'min_child_weight': 18.606153782157303, 'gamma': 1.03903257471111, 'reg_alpha': 0.4790847360483518, 'reg_lambda': 1.6027038767890223}. Best is trial 6 with value: 0.5938659587616151.

Best trial: 6. Best value: 0.593866:  20%|██        | 8/40 [00:26<02:04,  3.90s/it]

[I 2026-02-27 04:12:38,380] Trial 7 finished with value: 0.577059094781296 and parameters: {'n_estimators': 352, 'max_depth': 5, 'learning_rate': 0.03001844402818097, 'subsample': 0.5717413731571281, 'colsample_bytree': 0.6390120173940149, 'min_child_weight': 18.321993630405156, 'gamma': 3.6547323118946244, 'reg_alpha': 0.17510216760991082, 'reg_lambda': 3.7872262510978283}. Best is trial 6 with value: 0.5938659587616151.

Best trial: 6. Best value: 0.593866:  22%|██▎       | 9/40 [00:29<01:56,  3.74s/it]

[I 2026-02-27 04:12:41,776] Trial 8 finished with value: 0.5902901579809232 and parameters: {'n_estimators': 284, 'max_depth': 4, 'learning_rate': 0.08866692315875908, 'subsample': 0.5270909688790808, 'colsample_bytree': 0.5851000841921646, 'min_child_weight': 11.476900995320817, 'gamma': 1.5551912602136269, 'reg_alpha': 0.28953846448876264, 'reg_lambda': 1.182708976433256}. Best is trial 6 with value: 0.5938659587616151.

Best trial: 6. Best value: 0.593866:  25%|██▌       | 10/40 [00:31<01:36,  3.22s/it]

[I 2026-02-27 04:12:43,813] Trial 9 finished with value: 0.45597852773763814 and parameters: {'n_estimators': 205, 'max_depth': 3, 'learning_rate': 0.041258718407027786, 'subsample': 0.6147785074398419, 'colsample_bytree': 0.6772978707559526, 'min_child_weight': 8.38188245143673, 'gamma': 0.6728256878627423, 'reg_alpha': 0.6659788668654564, 'reg_lambda': 4.41810784515819}. Best is trial 6 with value: 0.5938659587616151.

Best trial: 6. Best value: 0.593866:  28%|██▊       | 11/40 [00:37<01:55,  4.00s/it]

[I 2026-02-27 04:12:49,581] Trial 10 finished with value: 0.5250099288485066 and parameters: {'n_estimators': 397, 'max_depth': 4, 'learning_rate': 0.023240702263628264, 'subsample': 0.712678290657434, 'colsample_bytree': 0.7073800898763567, 'min_child_weight': 15.173902393246173, 'gamma': 0.5643395742279331, 'reg_alpha': 0.3447976869660635, 'reg_lambda': 2.2767064542716056}. Best is trial 6 with value: 0.5938659587616151.

Best trial: 11. Best value: 0.595052:  30%|███       | 12/40 [00:41<01:51,  3.97s/it]

[I 2026-02-27 04:12:53,502] Trial 11 finished with value: 0.5950522625912613 and parameters: {'n_estimators': 293, 'max_depth': 4, 'learning_rate': 0.09898716685464305, 'subsample': 0.5265166354194062, 'colsample_bytree': 0.6260322697498608, 'min_child_weight': 11.378065651268674, 'gamma': 1.6093747177962718, 'reg_alpha': 0.004973619294558862, 'reg_lambda': 1.0370925523697057}. Best is trial 11 with value: 0.5950522625912613.

Best trial: 12. Best value: 0.596238:  32%|███▎      | 13/40 [00:45<01:45,  3.93s/it]

[I 2026-02-27 04:12:57,314] Trial 12 finished with value: 0.5962378057284543 and parameters: {'n_estimators': 316, 'max_depth': 4, 'learning_rate': 0.0897477409404379, 'subsample': 0.5058244795186904, 'colsample_bytree': 0.6391209605235272, 'min_child_weight': 11.968238061802142, 'gamma': 1.4937070478431993, 'reg_alpha': 0.00950873315971569, 'reg_lambda': 1.6057263584916537}. Best is trial 12 with value: 0.5962378057284543.

Best trial: 13. Best value: 0.634228:  35%|███▌      | 14/40 [00:49<01:45,  4.08s/it]

[I 2026-02-27 04:13:01,735] Trial 13 finished with value: 0.6342284884369945 and parameters: {'n_estimators': 301, 'max_depth': 5, 'learning_rate': 0.09858980072905238, 'subsample': 0.5010074152630751, 'colsample_bytree': 0.6199909689078918, 'min_child_weight': 11.421752860368812, 'gamma': 2.0837303730015586, 'reg_alpha': 0.0021683330304425675, 'reg_lambda': 2.8242455992117828}. Best is trial 13 with value: 0.6342284884369945.

Best trial: 13. Best value: 0.634228:  38%|███▊      | 15/40 [00:54<01:46,  4.28s/it]

[I 2026-02-27 04:13:06,486] Trial 14 finished with value: 0.6280213306853645 and parameters: {'n_estimators': 324, 'max_depth': 5, 'learning_rate': 0.07653794547187343, 'subsample': 0.5140015243088877, 'colsample_bytree': 0.7283880196180516, 'min_child_weight': 13.9625769493714, 'gamma': 2.342988762055697, 'reg_alpha': 0.0067789514181850336, 'reg_lambda': 2.838054209298476}. Best is trial 13 with value: 0.6342284884369945.

Best trial: 13. Best value: 0.634228:  40%|████      | 16/40 [00:58<01:44,  4.36s/it]

[I 2026-02-27 04:13:11,047] Trial 15 finished with value: 0.6256220093437678 and parameters: {'n_estimators': 318, 'max_depth': 5, 'learning_rate': 0.07535408732077074, 'subsample': 0.5045002819987633, 'colsample_bytree': 0.7272498440429086, 'min_child_weight': 14.642049544717024, 'gamma': 2.3550677842761596, 'reg_alpha': 0.14282102560020132, 'reg_lambda': 2.848336404225581}. Best is trial 13 with value: 0.6342284884369945.

Best trial: 13. Best value: 0.634228:  42%|████▎     | 17/40 [01:02<01:36,  4.18s/it]

[I 2026-02-27 04:13:14,809] Trial 16 finished with value: 0.568053876079299 and parameters: {'n_estimators': 268, 'max_depth': 5, 'learning_rate': 0.031041505541453945, 'subsample': 0.548288511662661, 'colsample_bytree': 0.7340877025855558, 'min_child_weight': 9.525519470608533, 'gamma': 3.0485169686029474, 'reg_alpha': 0.1491514891650744, 'reg_lambda': 2.937945945650386}. Best is trial 13 with value: 0.6342284884369945.

Best trial: 13. Best value: 0.634228:  45%|████▌     | 18/40 [01:07<01:34,  4.27s/it]

[I 2026-02-27 04:13:19,297] Trial 17 finished with value: 0.6314266431669523 and parameters: {'n_estimators': 321, 'max_depth': 5, 'learning_rate': 0.07012347426193744, 'subsample': 0.6274401666266427, 'colsample_bytree': 0.7006435098771461, 'min_child_weight': 14.223157624036851, 'gamma': 2.0178056875342834, 'reg_alpha': 0.3613177771068887, 'reg_lambda': 4.876569352249941}. Best is trial 13 with value: 0.6342284884369945.

Best trial: 13. Best value: 0.634228:  48%|████▊     | 19/40 [01:10<01:25,  4.06s/it]

[I 2026-02-27 04:13:22,856] Trial 18 finished with value: 0.5262840381892213 and parameters: {'n_estimators': 244, 'max_depth': 5, 'learning_rate': 0.02158764778478004, 'subsample': 0.6423809991221817, 'colsample_bytree': 0.6010362524433029, 'min_child_weight': 9.92387376631902, 'gamma': 2.1004233099103713, 'reg_alpha': 0.3737535098558103, 'reg_lambda': 4.981115083391879}. Best is trial 13 with value: 0.6342284884369945.

Best trial: 13. Best value: 0.634228:  50%|█████     | 20/40 [01:14<01:20,  4.04s/it]

[I 2026-02-27 04:13:26,843] Trial 19 finished with value: 0.6073918775638383 and parameters: {'n_estimators': 278, 'max_depth': 5, 'learning_rate': 0.06549610135278174, 'subsample': 0.6857577617996357, 'colsample_bytree': 0.5004379100533486, 'min_child_weight': 16.422345283152154, 'gamma': 3.939078951376116, 'reg_alpha': 0.8148337578836476, 'reg_lambda': 4.464534427733098}. Best is trial 13 with value: 0.6342284884369945.

Best trial: 13. Best value: 0.634228:  52%|█████▎    | 21/40 [01:19<01:21,  4.27s/it]

[I 2026-02-27 04:13:31,664] Trial 20 finished with value: 0.6076332093944382 and parameters: {'n_estimators': 344, 'max_depth': 5, 'learning_rate': 0.04104671590720123, 'subsample': 0.7708600696461065, 'colsample_bytree': 0.6875354469579991, 'min_child_weight': 13.152816753786393, 'gamma': 3.0000743300597295, 'reg_alpha': 0.45319286648095125, 'reg_lambda': 4.996188833066823}. Best is trial 13 with value: 0.6342284884369945.

Best trial: 13. Best value: 0.634228:  55%|█████▌    | 22/40 [01:23<01:18,  4.36s/it]

[I 2026-02-27 04:13:36,240] Trial 21 finished with value: 0.6334908706397206 and parameters: {'n_estimators': 315, 'max_depth': 5, 'learning_rate': 0.07722151213461298, 'subsample': 0.617039470086417, 'colsample_bytree': 0.7307788095596601, 'min_child_weight': 14.14074581039152, 'gamma': 1.9542202901516916, 'reg_alpha': 0.2224983949985463, 'reg_lambda': 3.2385959461668974}. Best is trial 13 with value: 0.6342284884369945.

Best trial: 22. Best value: 0.645744:  57%|█████▊    | 23/40 [01:28<01:14,  4.38s/it]

[I 2026-02-27 04:13:40,654] Trial 22 finished with value: 0.6457437103447937 and parameters: {'n_estimators': 316, 'max_depth': 5, 'learning_rate': 0.09904658087920225, 'subsample': 0.6149812047016854, 'colsample_bytree': 0.6871228967659683, 'min_child_weight': 16.50715367090959, 'gamma': 1.9429773430298614, 'reg_alpha': 0.277037813035037, 'reg_lambda': 3.2459019531177167}. Best is trial 22 with value: 0.6457437103447937.

Best trial: 22. Best value: 0.645744:  60%|██████    | 24/40 [01:31<01:04,  4.01s/it]

[I 2026-02-27 04:13:43,815] Trial 23 finished with value: 0.6399067674470815 and parameters: {'n_estimators': 303, 'max_depth': 5, 'learning_rate': 0.0999764947786384, 'subsample': 0.5994175834301406, 'colsample_bytree': 0.7584543716217914, 'min_child_weight': 19.923403539047154, 'gamma': 1.7934565426327242, 'reg_alpha': 0.217496354237095, 'reg_lambda': 3.158729088218126}. Best is trial 22 with value: 0.6457437103447937.

Best trial: 22. Best value: 0.645744:  62%|██████▎   | 25/40 [01:34<00:56,  3.77s/it]

[I 2026-02-27 04:13:47,014] Trial 24 finished with value: 0.644299779772431 and parameters: {'n_estimators': 294, 'max_depth': 5, 'learning_rate': 0.09748824504563827, 'subsample': 0.6767334249896543, 'colsample_bytree': 0.7610678159429747, 'min_child_weight': 19.709482200347196, 'gamma': 1.2021199947639531, 'reg_alpha': 0.09387105786508797, 'reg_lambda': 2.4881086107077888}. Best is trial 22 with value: 0.6457437103447937.

Best trial: 22. Best value: 0.645744:  65%|██████▌   | 26/40 [01:37<00:49,  3.54s/it]

[I 2026-02-27 04:13:50,014] Trial 25 finished with value: 0.6421271199654353 and parameters: {'n_estimators': 300, 'max_depth': 5, 'learning_rate': 0.08824014766368808, 'subsample': 0.6720078058634437, 'colsample_bytree': 0.7585645028348788, 'min_child_weight': 19.95679467012611, 'gamma': 1.105767192671411, 'reg_alpha': 0.09949720858077288, 'reg_lambda': 2.546871382582234}. Best is trial 22 with value: 0.6457437103447937.

Best trial: 22. Best value: 0.645744:  68%|██████▊   | 27/40 [01:40<00:42,  3.29s/it]

[I 2026-02-27 04:13:52,722] Trial 26 finished with value: 0.6327489971132976 and parameters: {'n_estimators': 270, 'max_depth': 5, 'learning_rate': 0.08296993695570569, 'subsample': 0.6695324939769087, 'colsample_bytree': 0.7597805833666291, 'min_child_weight': 19.773820086475094, 'gamma': 1.0680003302347687, 'reg_alpha': 0.07605851208336849, 'reg_lambda': 2.4898119362158924}. Best is trial 22 with value: 0.6457437103447937.

Best trial: 22. Best value: 0.645744:  70%|███████   | 28/40 [01:42<00:35,  2.94s/it]

[I 2026-02-27 04:13:54,853] Trial 27 finished with value: 0.555543021922768 and parameters: {'n_estimators': 251, 'max_depth': 4, 'learning_rate': 0.05635446457823603, 'subsample': 0.6746456714334887, 'colsample_bytree': 0.749040539193277, 'min_child_weight': 16.499166560446085, 'gamma': 1.0003206823545288, 'reg_alpha': 0.10618675797371101, 'reg_lambda': 2.0516790760719634}. Best is trial 22 with value: 0.6457437103447937.

Best trial: 22. Best value: 0.645744:  72%|███████▎  | 29/40 [01:46<00:34,  3.18s/it]

[I 2026-02-27 04:13:58,582] Trial 28 finished with value: 0.6180878555866466 and parameters: {'n_estimators': 365, 'max_depth': 5, 'learning_rate': 0.04772946489376609, 'subsample': 0.7254171402201622, 'colsample_bytree': 0.6637107032130644, 'min_child_weight': 17.167748265906223, 'gamma': 1.2712628004216908, 'reg_alpha': 0.265290825094344, 'reg_lambda': 2.5816006461627516}. Best is trial 22 with value: 0.6457437103447937.

Best trial: 22. Best value: 0.645744:  75%|███████▌  | 30/40 [01:49<00:30,  3.09s/it]

[I 2026-02-27 04:14:01,475] Trial 29 finished with value: 0.5834490311447463 and parameters: {'n_estimators': 336, 'max_depth': 4, 'learning_rate': 0.0625872256061984, 'subsample': 0.6942764025473431, 'colsample_bytree': 0.7996639281838788, 'min_child_weight': 18.86311266278166, 'gamma': 4.83045145689111, 'reg_alpha': 0.08009647106794526, 'reg_lambda': 3.3467238130607244}. Best is trial 22 with value: 0.6457437103447937.

Best trial: 22. Best value: 0.645744:  78%|███████▊  | 31/40 [01:52<00:27,  3.06s/it]

[I 2026-02-27 04:14:04,475] Trial 30 finished with value: 0.5908965360997905 and parameters: {'n_estimators': 295, 'max_depth': 5, 'learning_rate': 0.037982219253674045, 'subsample': 0.6573505105445592, 'colsample_bytree': 0.7707360955480934, 'min_child_weight': 16.028217386869027, 'gamma': 0.7872775251885462, 'reg_alpha': 0.29721251548646627, 'reg_lambda': 1.8567960352200366}. Best is trial 22 with value: 0.6457437103447937.

Best trial: 22. Best value: 0.645744:  80%|████████  | 32/40 [01:55<00:24,  3.07s/it]

[I 2026-02-27 04:14:07,559] Trial 31 finished with value: 0.6384191650363946 and parameters: {'n_estimators': 296, 'max_depth': 5, 'learning_rate': 0.09970561490723666, 'subsample': 0.5898162129144442, 'colsample_bytree': 0.7505439934731839, 'min_child_weight': 19.88936731393834, 'gamma': 1.735949365135623, 'reg_alpha': 0.19667370109110732, 'reg_lambda': 3.2057435500657734}. Best is trial 22 with value: 0.6457437103447937.

Best trial: 22. Best value: 0.645744:  82%|████████▎ | 33/40 [01:58<00:21,  3.10s/it]

[I 2026-02-27 04:14:10,726] Trial 32 finished with value: 0.6374613001295353 and parameters: {'n_estimators': 307, 'max_depth': 5, 'learning_rate': 0.08487689214581887, 'subsample': 0.6323016470341415, 'colsample_bytree': 0.7658240778351776, 'min_child_weight': 19.18361586066187, 'gamma': 1.3451481174335984, 'reg_alpha': 0.23358117355213637, 'reg_lambda': 3.515814022980664}. Best is trial 22 with value: 0.6457437103447937.

Best trial: 22. Best value: 0.645744:  85%|████████▌ | 34/40 [02:01<00:18,  3.04s/it]

[I 2026-02-27 04:14:13,624] Trial 33 finished with value: 0.6326381013914293 and parameters: {'n_estimators': 283, 'max_depth': 5, 'learning_rate': 0.08633834168291189, 'subsample': 0.6051221289976836, 'colsample_bytree': 0.7102113009452367, 'min_child_weight': 17.609186186125743, 'gamma': 1.7644536600087877, 'reg_alpha': 0.1020080563754984, 'reg_lambda': 4.077618893805629}. Best is trial 22 with value: 0.6457437103447937.

Best trial: 22. Best value: 0.645744:  88%|████████▊ | 35/40 [02:04<00:14,  2.95s/it]

[I 2026-02-27 04:14:16,375] Trial 34 finished with value: 0.46499749618959163 and parameters: {'n_estimators': 260, 'max_depth': 5, 'learning_rate': 0.010311846878508928, 'subsample': 0.6634739014729908, 'colsample_bytree': 0.7791955933907044, 'min_child_weight': 18.051178193132216, 'gamma': 0.8766857369472985, 'reg_alpha': 0.16830619084094842, 'reg_lambda': 2.6593903976803204}. Best is trial 22 with value: 0.6457437103447937.

Best trial: 22. Best value: 0.645744:  90%|█████████ | 36/40 [02:06<00:11,  2.78s/it]

[I 2026-02-27 04:14:18,765] Trial 35 finished with value: 0.6037453324411726 and parameters: {'n_estimators': 233, 'max_depth': 5, 'learning_rate': 0.06129518265918251, 'subsample': 0.7394281722812043, 'colsample_bytree': 0.7538326142564009, 'min_child_weight': 19.841241348503992, 'gamma': 2.3720280519927255, 'reg_alpha': 0.43172352989288804, 'reg_lambda': 3.0389720934419304}. Best is trial 22 with value: 0.6457437103447937.

Best trial: 22. Best value: 0.645744:  92%|█████████▎| 37/40 [02:09<00:08,  2.84s/it]

[I 2026-02-27 04:14:21,740] Trial 36 finished with value: 0.6076293142967023 and parameters: {'n_estimators': 333, 'max_depth': 4, 'learning_rate': 0.09982794239732132, 'subsample': 0.5889081448687487, 'colsample_bytree': 0.7891653924144151, 'min_child_weight': 17.139133327104588, 'gamma': 1.2322771345423345, 'reg_alpha': 0.06684408152492295, 'reg_lambda': 2.338896363663123}. Best is trial 22 with value: 0.6457437103447937.

Best trial: 22. Best value: 0.645744:  95%|█████████▌| 38/40 [02:12<00:05,  2.95s/it]

[I 2026-02-27 04:14:24,956] Trial 37 finished with value: 0.6187153577187925 and parameters: {'n_estimators': 305, 'max_depth': 5, 'learning_rate': 0.07220371951422033, 'subsample': 0.5581556420515413, 'colsample_bytree': 0.6901601238648023, 'min_child_weight': 19.14195977819389, 'gamma': 2.679720872660642, 'reg_alpha': 0.5308565421878999, 'reg_lambda': 3.7922924055957834}. Best is trial 22 with value: 0.6457437103447937.

Best trial: 22. Best value: 0.645744:  98%|█████████▊| 39/40 [02:16<00:03,  3.19s/it]

[I 2026-02-27 04:14:28,714] Trial 38 finished with value: 0.6138718287698705 and parameters: {'n_estimators': 329, 'max_depth': 5, 'learning_rate': 0.04996070376186539, 'subsample': 0.6375761009751166, 'colsample_bytree': 0.7413473070494856, 'min_child_weight': 15.428582867943192, 'gamma': 1.8012056618025034, 'reg_alpha': 0.3195715335662568, 'reg_lambda': 3.125505429161766}. Best is trial 22 with value: 0.6457437103447937.

Best trial: 22. Best value: 0.645744: 100%|██████████| 40/40 [02:19<00:00,  3.49s/it]

[I 2026-02-27 04:14:31,843] Trial 39 finished with value: 0.5037483510964623 and parameters: {'n_estimators': 286, 'max_depth': 5, 'learning_rate': 0.014913621474072351, 'subsample': 0.6845867412882305, 'colsample_bytree': 0.5439289746911153, 'min_child_weight': 18.144029684182545, 'gamma': 3.404559224738736, 'reg_alpha': 0.3968412032657098, 'reg_lambda': 3.4173786648287487}. Best is trial 22 with value: 0.6457437103447937.
Best CV R²: 0.6457437103447937
Best params:
  n_estimators: 316
  max_depth: 5
  learning_rate: 0.09904658087920225
  subsample: 0.6149812047016854
  colsample_bytree: 0.6871228967659683
  min_child_weight: 16.50715367090959
  gamma: 1.9429773430298614
  reg_alpha: 0.277037813035037
  reg_lambda: 3.2459019531177167

In [16]:
# Train final model with best hyperparameters and report R² + feature importances

best_params = study.best_params.copy()
best_params.update({"random_state": 42, "n_jobs": -1})

final_model = xgb.XGBRegressor(**best_params)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

final_model.fit(
    X_train,
    y_train,
    eval_set=[(X_test, y_test)],
    verbose=False,
)

y_train_pred = final_model.predict(X_train)
y_test_pred = final_model.predict(X_test)

r2_train = r2_score(y_train, y_train_pred)
r2_test = r2_score(y_test, y_test_pred)

print(f"Final model (with tuned params) Train R²: {r2_train:.3f}")
print(f"Final model (with tuned params) Test  R²: {r2_test:.3f}")

# Feature importances from tuned model
importances = final_model.feature_importances_
fi_tuned = pd.DataFrame({"feature": feature_cols, "importance": importances})
fi_tuned = fi_tuned.sort_values("importance", ascending=False)

print("\nTop 20 most important features for predicting EC (tuned model):")
print(fi_tuned.head(40).to_string(index=False))

fi_tuned.head(40)

Final model (with tuned params) Train R²: 0.833
Final model (with tuned params) Test  R²: 0.672

Top 20 most important features for predicting EC (tuned model):
         feature  importance
            soil    0.138058
esa_change_count    0.119260
  esa_lccs_class    0.090733
             vpd    0.056925
          swir16    0.052426
             def    0.051892
           MNDWI    0.046568
            pdsi    0.046547
             pet    0.046156
             vap    0.043661
            tmin    0.038823
            NDMI    0.038216
    month_fitted    0.037536
             aet    0.037082
             red    0.035324
              ws    0.033640
            tmax    0.030301
             ppt    0.029252
               q    0.027601

             feature  importance
0               soil    0.138058
1   esa_change_count    0.119260
2     esa_lccs_class    0.090733
3                vpd    0.056925
13            swir16    0.052426
10               def    0.051892
5              MNDWI    0.046568
6               pdsi    0.046547
9                pet    0.046156
4                vap    0.043661
8               tmin    0.038823
12              NDMI    0.038216
18      month_fitted    0.037536
15               aet    0.037082
14               red    0.035324
7                 ws    0.033640
16              tmax    0.030301
11               ppt    0.029252
17                 q    0.027601

In [17]:
# Create predictions for EC on validation data and update submission file

# Load submission template
sub_template = pd.read_csv("../../submission_template.csv")
print("Submission template shape:", sub_template.shape)
print("Template columns:", list(sub_template.columns))

# VALIDATION CHECK: Ensure template has exactly 200 rows
assert sub_template.shape[0] == 200, f"Template should have 200 rows, found {sub_template.shape[0]}!"

# Load validation features
val_features = pd.read_csv("../../Datasets_Ours/Final Datasets/ec_validation.csv")
print("\nValidation dataset shape:", val_features.shape)
print("Validation columns:", list(val_features.columns))

# VALIDATION CHECK: Ensure validation has exactly 200 rows
assert val_features.shape[0] == 200, f"Validation should have 200 rows, found {val_features.shape[0]}!"

# Build X for validation using the same selected feature set as training
X_val = val_features[feature_cols].copy()
print("\nValidation features shape:", X_val.shape)
print(f"Using {len(feature_cols)} features: {feature_cols[:5]}...")

# Predict EC for validation rows
ec_pred = final_model.predict(X_val)
print(f"\nGenerated {len(ec_pred)} EC predictions")
print(f"EC predictions - Min: {ec_pred.min():.2f}, Max: {ec_pred.max():.2f}, Mean: {ec_pred.mean():.2f}")

# CRITICAL: Match predictions to template by LAT/LON/DATE (not row order!)
val_features['EC_prediction'] = ec_pred

# Standardize column names for merge
val_features_std = val_features.rename(columns={
    'latitude': 'Latitude',
    'longitude': 'Longitude',
    'sample_date': 'Sample Date'
})

# Merge predictions with template by coordinates AND date
submission = sub_template.merge(
    val_features_std[['Latitude', 'Longitude', 'Sample Date', 'EC_prediction']],
    on=['Latitude', 'Longitude', 'Sample Date'],
    how='left'
)

# Rename prediction column
submission['Electrical Conductance'] = submission['EC_prediction']
submission = submission.drop(columns=['EC_prediction'])

# Ensure column order matches template
submission = submission[sub_template.columns]

# VALIDATION CHECK: Ensure no missing predictions
missing_count = submission['Electrical Conductance'].isnull().sum()
if missing_count > 0:
    print(f"\n⚠️  WARNING: {missing_count} locations without EC predictions!")
    print("Missing locations:")
    print(submission[submission['Electrical Conductance'].isnull()][['Latitude', 'Longitude', 'Sample Date']].head(10))
else:
    print("\n✓ All 200 locations have EC predictions")

# Save submission file
out_path = "../../submission1.csv"
submission.to_csv(out_path, index=False)
print(f"\nSaved submission file: {out_path}")
print("Submission shape:", submission.shape)
print("\nFirst few rows of submission:")
submission.head()

Submission template shape: (200, 6)
Template columns: ['Latitude', 'Longitude', 'Sample Date', 'Total Alkalinity', 'Electrical Conductance', 'Dissolved Reactive Phosphorus']

Validation dataset shape: (200, 24)
Validation columns: ['latitude', 'longitude', 'sample_date', 'month_fitted', 'swir16', 'swir22', 'red', 'NDMI', 'MNDWI', 'pet', 'aet', 'def', 'q', 'ppt', 'soil', 'srad', 'tmax', 'tmin', 'vap', 'vpd', 'ws', 'pdsi', 'esa_lccs_class', 'esa_change_count']

Validation features shape: (200, 19)
Using 19 features: ['soil', 'esa_change_count', 'esa_lccs_class', 'vpd', 'vap']...

Generated 200 EC predictions
EC predictions - Min: 87.18, Max: 791.43, Mean: 372.91

✓ All 200 locations have EC predictions

Saved submission file: ../../submission1.csv
Submission shape: (200, 6)

First few rows of submission:

,Latitude,Longitude,Sample Date,Total Alkalinity,Electrical Conductance,Dissolved Reactive Phosphorus
0,-32.043333,27.822778,01-09-2014,NaN,289.397919,NaN
1,-33.329167,26.077500,16-09-2015,NaN,440.410156,NaN
2,-32.991639,27.640028,07-05-2015,NaN,295.260529,NaN
3,-34.096389,24.439167,07-02-2012,NaN,393.329376,NaN
4,-32.000556,28.581667,01-10-2014,NaN,199.030121,NaN