In [1]:
# Model1: XGBoost model to predict Total Alkalinity (TA)

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.metrics import r2_score

import optuna  # pip install optuna
import xgboost as xgb  # pip install xgboost

/Users/ethan/Library/Python/3.10/lib/python/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# Load TA training dataset (features + target already joined)

data_path = "../../New Datasets/Combined/Final Datasets/ta_training_complete.csv"
full = pd.read_csv(data_path)

print("TA Training dataset shape:", full.shape)
print("Columns:", list(full.columns))
full.head()

TA Training dataset shape: (9319, 24)
Columns: ['latitude', 'longitude', 'month_fitted', 'swir16', 'swir22', 'red', 'NDMI', 'MNDWI', 'pet', 'aet', 'def', 'q', 'ppt', 'soil', 'srad', 'tmax', 'tmin', 'vap', 'vpd', 'ws', 'pdsi', 'esa_lccs_class', 'esa_change_count', 'total_alkalinity']

,latitude,longitude,month_fitted,swir16,swir22,red,NDMI,MNDWI,pet,aet,...,srad,tmax,tmin,vap,vpd,ws,pdsi,esa_lccs_class,esa_change_count,total_alkalinity
0,-34.405833,19.600556,127.924326,13580.000000,10717.000000,9095.500000,0.166424,-0.184320,132.300003,11.900001,...,263.801483,23.480000,12.179999,1.372,0.79,3.48,-2.59,120.0,0.0,54.181
1,-34.405833,19.600556,130.915586,13929.063497,11630.326299,10277.402037,0.020388,-0.164582,70.400002,67.599998,...,158.596588,17.779999,7.240000,1.004,0.53,3.36,-3.30,120.0,0.0,36.247
2,-34.405833,19.600556,116.838708,14115.066596,11794.309348,10413.610383,0.009226,-0.173084,163.000000,18.000000,...,323.498383,26.469999,15.740000,1.703,0.93,2.07,-3.49,120.0,0.0,57.800
3,-34.405833,19.600556,128.312603,11536.500000,9401.000000,8631.000000,0.129337,-0.139379,51.400002,43.700001,...,113.603378,17.420000,8.400000,1.106,0.45,3.50,-1.60,120.0,0.0,29.719
4,-34.405833,19.600556,130.776727,13263.500000,10589.000000,9197.500000,0.139460,-0.176520,88.200005,58.600002,...,195.097321,19.730000,10.200000,1.231,0.55,3.64,-1.40,120.0,0.0,58.231

In [3]:
# Build feature matrix X and target y for TA

# Columns to exclude from features
exclude_cols = {
    "total_alkalinity",                 # target
    "latitude", "longitude",            # spatial identifiers
}

base_feature_cols = [c for c in full.columns if c not in exclude_cols]
X_full = full[base_feature_cols].copy()
y = full["total_alkalinity"]

print("Initial number of features:", len(base_feature_cols))
print("Features:", base_feature_cols)

# 1) Remove multicollinearity: drop one of each highly correlated pair
corr_matrix = X_full.corr().abs()
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))

high_corr_threshold = 0.95
cols_to_drop_mc = [col for col in upper.columns if any(upper[col] > high_corr_threshold)]

X_mc = X_full.drop(columns=cols_to_drop_mc)
feature_cols_mc = list(X_mc.columns)

print(f"Dropped {len(cols_to_drop_mc)} highly correlated features (>|{high_corr_threshold}|)")
print("Remaining features after multicollinearity reduction:", len(feature_cols_mc))

# Expose reduced set for feature selection
X_reduced_mc = X_mc.copy()
feature_cols_reduced_mc = feature_cols_mc

print("Example remaining feature columns:", feature_cols_reduced_mc[:10])

Initial number of features: 21
Features: ['month_fitted', 'swir16', 'swir22', 'red', 'NDMI', 'MNDWI', 'pet', 'aet', 'def', 'q', 'ppt', 'soil', 'srad', 'tmax', 'tmin', 'vap', 'vpd', 'ws', 'pdsi', 'esa_lccs_class', 'esa_change_count']
Dropped 2 highly correlated features (>|0.95|)
Remaining features after multicollinearity reduction: 19
Example remaining feature columns: ['month_fitted', 'swir16', 'red', 'NDMI', 'MNDWI', 'pet', 'aet', 'def', 'q', 'ppt']

In [4]:
# Feature selection via XGBoost feature importance (on multicollinearity-reduced set)

fs_model = xgb.XGBRegressor(
    n_estimators=400,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1,
)

fs_model.fit(X_reduced_mc, y)

importances = fs_model.feature_importances_
fi_fs = pd.DataFrame({"feature": feature_cols_reduced_mc, "importance": importances})
fi_fs = fi_fs.sort_values("importance", ascending=False).reset_index(drop=True)
fi_fs["cum_importance"] = fi_fs["importance"].cumsum()

# Keep features that explain up to 90% of total importance, but ensure at least 20 features
importance_cutoff = 0.90
min_features = 20
selected = fi_fs[fi_fs["cum_importance"] <= importance_cutoff]["feature"].tolist()
if len(selected) < min_features:
    selected = fi_fs.head(min_features)["feature"].tolist()

X = X_reduced_mc[selected].copy()
feature_cols = selected

print("Total features after multicollinearity reduction:", len(feature_cols_reduced_mc))
print("Selected features after importance-based selection:", len(feature_cols))
print("Top selected features:", feature_cols[:15])

Total features after multicollinearity reduction: 19
Selected features after importance-based selection: 19
Top selected features: ['soil', 'esa_lccs_class', 'vpd', 'vap', 'esa_change_count', 'MNDWI', 'tmin', 'ppt', 'pdsi', 'NDMI', 'ws', 'swir16', 'pet', 'red', 'tmax']

In [5]:
# Baseline XGBoost model (for quick R² and importances)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = xgb.XGBRegressor(
    n_estimators=400,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1,
)

model.fit(X_train, y_train)

y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

print(f"Baseline Train R²: {r2_score(y_train, y_train_pred):.3f}")
print(f"Baseline Test  R²: {r2_score(y_test, y_test_pred):.3f}")

importances_base = model.feature_importances_
fi_base = pd.DataFrame({"feature": feature_cols, "importance": importances_base})
fi_base.sort_values("importance", ascending=False).head(20)

Baseline Train R²: 0.903
Baseline Test  R²: 0.690

             feature  importance
0               soil    0.113759
1     esa_lccs_class    0.099406
2                vpd    0.072176
3                vap    0.059773
6               tmin    0.059667
11            swir16    0.056567
9               NDMI    0.052904
4   esa_change_count    0.049070
13               red    0.044386
8               pdsi    0.044293
10                ws    0.044064
16               aet    0.043983
5              MNDWI    0.042291
12               pet    0.039551
14              tmax    0.038206
15               def    0.037293
17      month_fitted    0.036109
18                 q    0.033755
7                ppt    0.032746

In [6]:
# Stratified K-Fold + Optuna hyperparameter tuning for TA model

n_bins = 10
y_strat = pd.qcut(y, q=n_bins, labels=False, duplicates='drop')

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

def objective(trial: optuna.trial.Trial) -> float:
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 200, 400),
        "max_depth": trial.suggest_int("max_depth", 3, 5),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.1, log=True),
        "subsample": trial.suggest_float("subsample", 0.5, 0.8),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 0.8),
        "min_child_weight": trial.suggest_float("min_child_weight", 5.0, 20.0),
        "gamma": trial.suggest_float("gamma", 0.5, 5.0),
        "reg_alpha": trial.suggest_float("reg_alpha", 0.0, 1.0),
        "reg_lambda": trial.suggest_float("reg_lambda", 1.0, 5.0),
        "random_state": 42,
        "n_jobs": -1,
    }

    model = xgb.XGBRegressor(**params)

    cv_scores = []
    for train_idx, valid_idx in skf.split(X, y_strat):
        X_tr, X_val = X.iloc[train_idx], X.iloc[valid_idx]
        y_tr, y_val = y.iloc[train_idx], y.iloc[valid_idx]

        model.fit(
            X_tr,
            y_tr,
            eval_set=[(X_val, y_val)],
            verbose=False,
        )
        y_val_pred = model.predict(X_val)
        cv_scores.append(r2_score(y_val, y_val_pred))

    return float(np.mean(cv_scores))

study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=40, show_progress_bar=True)

print("Best CV R²:", study.best_value)
print("Best params:")
for k, v in study.best_params.items():
    print(f"  {k}: {v}")

[I 2026-02-27 04:11:28,502] A new study created in memory with name: no-name-179385a3-b558-487d-b541-9ea4517cd033
Best trial: 0. Best value: 0.499403:   2%|▎         | 1/40 [00:02<01:45,  2.70s/it]

[I 2026-02-27 04:11:31,208] Trial 0 finished with value: 0.4994031580113519 and parameters: {'n_estimators': 323, 'max_depth': 5, 'learning_rate': 0.012681151281420604, 'subsample': 0.6273752555821094, 'colsample_bytree': 0.5546116197692579, 'min_child_weight': 17.82437236678216, 'gamma': 2.219868143668867, 'reg_alpha': 0.6326093263322038, 'reg_lambda': 4.095809342964779}. Best is trial 0 with value: 0.4994031580113519.

Best trial: 0. Best value: 0.499403:   5%|▌         | 2/40 [00:04<01:22,  2.16s/it]

[I 2026-02-27 04:11:32,997] Trial 1 finished with value: 0.4387361151773149 and parameters: {'n_estimators': 388, 'max_depth': 3, 'learning_rate': 0.01702280116802573, 'subsample': 0.7361133048114895, 'colsample_bytree': 0.5288856159713576, 'min_child_weight': 10.023979390658255, 'gamma': 1.0008811384375886, 'reg_alpha': 0.13715577189843242, 'reg_lambda': 3.4738440344586436}. Best is trial 0 with value: 0.4994031580113519.

Best trial: 2. Best value: 0.576341:   8%|▊         | 3/40 [00:06<01:10,  1.91s/it]

[I 2026-02-27 04:11:34,607] Trial 2 finished with value: 0.5763413583539209 and parameters: {'n_estimators': 237, 'max_depth': 5, 'learning_rate': 0.03914608074814448, 'subsample': 0.591599155912834, 'colsample_bytree': 0.7677843540560036, 'min_child_weight': 13.36379447264942, 'gamma': 4.191281124576267, 'reg_alpha': 0.2749151318358548, 'reg_lambda': 2.083962294946078}. Best is trial 2 with value: 0.5763413583539209.

Best trial: 3. Best value: 0.638657:  10%|█         | 4/40 [00:08<01:15,  2.08s/it]

[I 2026-02-27 04:11:36,955] Trial 3 finished with value: 0.6386571350439105 and parameters: {'n_estimators': 349, 'max_depth': 5, 'learning_rate': 0.06800757560405603, 'subsample': 0.5797811772518068, 'colsample_bytree': 0.724418288230177, 'min_child_weight': 11.347958307138107, 'gamma': 2.777500590934199, 'reg_alpha': 0.14154452923406868, 'reg_lambda': 4.4218253947777075}. Best is trial 3 with value: 0.6386571350439105.

Best trial: 3. Best value: 0.638657:  12%|█▎        | 5/40 [00:10<01:09,  2.00s/it]

[I 2026-02-27 04:11:38,800] Trial 4 finished with value: 0.5158077629438635 and parameters: {'n_estimators': 364, 'max_depth': 3, 'learning_rate': 0.05233888865354884, 'subsample': 0.6500309194326003, 'colsample_bytree': 0.6148345405984134, 'min_child_weight': 17.04528073982668, 'gamma': 1.9419544734365237, 'reg_alpha': 0.8289780980611594, 'reg_lambda': 2.082830188556338}. Best is trial 3 with value: 0.6386571350439105.

Best trial: 3. Best value: 0.638657:  15%|█▌        | 6/40 [00:11<00:57,  1.70s/it]

[I 2026-02-27 04:11:39,915] Trial 5 finished with value: 0.3824149723020086 and parameters: {'n_estimators': 248, 'max_depth': 3, 'learning_rate': 0.012887010162351158, 'subsample': 0.5001557368214653, 'colsample_bytree': 0.7047171543572002, 'min_child_weight': 16.622344816279632, 'gamma': 1.151898417675099, 'reg_alpha': 0.916492549800077, 'reg_lambda': 2.2699246139335205}. Best is trial 3 with value: 0.6386571350439105.

Best trial: 3. Best value: 0.638657:  18%|█▊        | 7/40 [00:13<00:55,  1.69s/it]

[I 2026-02-27 04:11:41,589] Trial 6 finished with value: 0.6052659781453185 and parameters: {'n_estimators': 257, 'max_depth': 5, 'learning_rate': 0.06163345804959951, 'subsample': 0.5170828317054764, 'colsample_bytree': 0.7297393654951353, 'min_child_weight': 17.246562887075378, 'gamma': 4.9072325496188975, 'reg_alpha': 0.05346692110596196, 'reg_lambda': 1.610977437820833}. Best is trial 3 with value: 0.6386571350439105.

Best trial: 3. Best value: 0.638657:  20%|██        | 8/40 [00:14<00:49,  1.56s/it]

[I 2026-02-27 04:11:42,858] Trial 7 finished with value: 0.534469793942988 and parameters: {'n_estimators': 300, 'max_depth': 3, 'learning_rate': 0.08530494420307473, 'subsample': 0.5120633973235942, 'colsample_bytree': 0.589920803921, 'min_child_weight': 16.886800186773538, 'gamma': 1.4494448757188472, 'reg_alpha': 0.7970555555759692, 'reg_lambda': 3.523981223819943}. Best is trial 3 with value: 0.6386571350439105.

Best trial: 3. Best value: 0.638657:  22%|██▎       | 9/40 [00:15<00:46,  1.51s/it]

[I 2026-02-27 04:11:44,274] Trial 8 finished with value: 0.43243383479035036 and parameters: {'n_estimators': 313, 'max_depth': 3, 'learning_rate': 0.018085963392464353, 'subsample': 0.6063983652207047, 'colsample_bytree': 0.7781543943561352, 'min_child_weight': 12.689010681669588, 'gamma': 2.8976746463132295, 'reg_alpha': 0.5355270067270281, 'reg_lambda': 2.6251008783272978}. Best is trial 3 with value: 0.6386571350439105.

Best trial: 3. Best value: 0.638657:  25%|██▌       | 10/40 [00:18<00:54,  1.80s/it]

[I 2026-02-27 04:11:46,729] Trial 9 finished with value: 0.5165266000487942 and parameters: {'n_estimators': 372, 'max_depth': 5, 'learning_rate': 0.012787326746391776, 'subsample': 0.5126042603470666, 'colsample_bytree': 0.7790860460078102, 'min_child_weight': 18.215630573395618, 'gamma': 1.7476084966456549, 'reg_alpha': 0.5384921255691324, 'reg_lambda': 3.2491258411917197}. Best is trial 3 with value: 0.6386571350439105.

Best trial: 3. Best value: 0.638657:  28%|██▊       | 11/40 [00:19<00:47,  1.63s/it]

[I 2026-02-27 04:11:47,966] Trial 10 finished with value: 0.5894630239396731 and parameters: {'n_estimators': 207, 'max_depth': 4, 'learning_rate': 0.09904741793567728, 'subsample': 0.7909259074705923, 'colsample_bytree': 0.6616092247698407, 'min_child_weight': 5.063151387648676, 'gamma': 3.5400720949616713, 'reg_alpha': 0.23588948810934646, 'reg_lambda': 4.960142697956627}. Best is trial 3 with value: 0.6386571350439105.

Best trial: 3. Best value: 0.638657:  30%|███       | 12/40 [00:20<00:44,  1.60s/it]

[I 2026-02-27 04:11:49,483] Trial 11 finished with value: 0.5781979185359486 and parameters: {'n_estimators': 278, 'max_depth': 4, 'learning_rate': 0.06023795775340375, 'subsample': 0.576622779138313, 'colsample_bytree': 0.7104653385221342, 'min_child_weight': 9.638259576720323, 'gamma': 4.720870415380514, 'reg_alpha': 0.005862961972132409, 'reg_lambda': 1.1354847404808899}. Best is trial 3 with value: 0.6386571350439105.

Best trial: 3. Best value: 0.638657:  32%|███▎      | 13/40 [00:23<00:47,  1.77s/it]

[I 2026-02-27 04:11:51,666] Trial 12 finished with value: 0.5787345300333435 and parameters: {'n_estimators': 342, 'max_depth': 5, 'learning_rate': 0.029691887467429054, 'subsample': 0.5570684839880592, 'colsample_bytree': 0.7255104638102201, 'min_child_weight': 19.95950964402627, 'gamma': 3.267359584600185, 'reg_alpha': 0.014637165765947868, 'reg_lambda': 1.0090658875525331}. Best is trial 3 with value: 0.6386571350439105.

Best trial: 3. Best value: 0.638657:  35%|███▌      | 14/40 [00:24<00:43,  1.68s/it]

[I 2026-02-27 04:11:53,121] Trial 13 finished with value: 0.5703441457512147 and parameters: {'n_estimators': 267, 'max_depth': 4, 'learning_rate': 0.06295740808119908, 'subsample': 0.6877141065513653, 'colsample_bytree': 0.660365209254582, 'min_child_weight': 14.137130937865287, 'gamma': 4.877894105516916, 'reg_alpha': 0.3967863682566946, 'reg_lambda': 4.956686529858564}. Best is trial 3 with value: 0.6386571350439105.

Best trial: 3. Best value: 0.638657:  38%|███▊      | 15/40 [00:26<00:46,  1.86s/it]

[I 2026-02-27 04:11:55,409] Trial 14 finished with value: 0.5943776116449034 and parameters: {'n_estimators': 339, 'max_depth': 5, 'learning_rate': 0.034826554705018165, 'subsample': 0.5485346962508677, 'colsample_bytree': 0.7373095007879009, 'min_child_weight': 9.889797148449393, 'gamma': 3.89546414441845, 'reg_alpha': 0.17539577738517098, 'reg_lambda': 4.073822672325124}. Best is trial 3 with value: 0.6386571350439105.

Best trial: 3. Best value: 0.638657:  40%|████      | 16/40 [00:28<00:40,  1.70s/it]

[I 2026-02-27 04:11:56,720] Trial 15 finished with value: 0.6131571767462229 and parameters: {'n_estimators': 202, 'max_depth': 5, 'learning_rate': 0.07670451519445531, 'subsample': 0.5474773311201363, 'colsample_bytree': 0.663933496702303, 'min_child_weight': 7.505975525581176, 'gamma': 0.6073486332859921, 'reg_alpha': 0.341519761798412, 'reg_lambda': 1.4804840409534752}. Best is trial 3 with value: 0.6386571350439105.

Best trial: 3. Best value: 0.638657:  42%|████▎     | 17/40 [00:29<00:35,  1.55s/it]

[I 2026-02-27 04:11:57,915] Trial 16 finished with value: 0.570478036500441 and parameters: {'n_estimators': 203, 'max_depth': 4, 'learning_rate': 0.08406721089324803, 'subsample': 0.6894506504561149, 'colsample_bytree': 0.6772256082065102, 'min_child_weight': 7.074370135761846, 'gamma': 0.5886036941465685, 'reg_alpha': 0.33538120952312145, 'reg_lambda': 4.264740116025172}. Best is trial 3 with value: 0.6386571350439105.

Best trial: 3. Best value: 0.638657:  45%|████▌     | 18/40 [00:31<00:36,  1.66s/it]

[I 2026-02-27 04:11:59,830] Trial 17 finished with value: 0.604386655493356 and parameters: {'n_estimators': 293, 'max_depth': 5, 'learning_rate': 0.04707046890618223, 'subsample': 0.5533931532704109, 'colsample_bytree': 0.6269558050808182, 'min_child_weight': 8.27060402261735, 'gamma': 2.6217379290930554, 'reg_alpha': 0.40076741061873106, 'reg_lambda': 2.7724528245912765}. Best is trial 3 with value: 0.6386571350439105.

Best trial: 3. Best value: 0.638657:  48%|████▊     | 19/40 [00:32<00:32,  1.56s/it]

[I 2026-02-27 04:12:01,153] Trial 18 finished with value: 0.5026155846022616 and parameters: {'n_estimators': 229, 'max_depth': 4, 'learning_rate': 0.02869404987423759, 'subsample': 0.6499551260453499, 'colsample_bytree': 0.6852019118223356, 'min_child_weight': 11.236795645199802, 'gamma': 2.4809019712916283, 'reg_alpha': 0.6473993793322943, 'reg_lambda': 1.6160873108172427}. Best is trial 3 with value: 0.6386571350439105.

Best trial: 19. Best value: 0.652903:  50%|█████     | 20/40 [00:35<00:37,  1.90s/it]

[I 2026-02-27 04:12:03,854] Trial 19 finished with value: 0.6529026058349405 and parameters: {'n_estimators': 400, 'max_depth': 5, 'learning_rate': 0.07870980220443116, 'subsample': 0.6204026874541693, 'colsample_bytree': 0.6267564399827514, 'min_child_weight': 6.219625306393248, 'gamma': 3.058275533126669, 'reg_alpha': 0.12459376106235664, 'reg_lambda': 4.613570482896999}. Best is trial 19 with value: 0.6529026058349405.

Best trial: 19. Best value: 0.652903:  52%|█████▎    | 21/40 [00:37<00:38,  2.02s/it]

[I 2026-02-27 04:12:06,149] Trial 20 finished with value: 0.5188378390323882 and parameters: {'n_estimators': 390, 'max_depth': 4, 'learning_rate': 0.02194241425705559, 'subsample': 0.6188274530095016, 'colsample_bytree': 0.5852658776686873, 'min_child_weight': 5.340869383954804, 'gamma': 3.0713564111676415, 'reg_alpha': 0.12247594174197193, 'reg_lambda': 4.426648803966765}. Best is trial 19 with value: 0.6529026058349405.

Best trial: 19. Best value: 0.652903:  55%|█████▌    | 22/40 [00:40<00:38,  2.16s/it]

[I 2026-02-27 04:12:08,643] Trial 21 finished with value: 0.6482256922662633 and parameters: {'n_estimators': 355, 'max_depth': 5, 'learning_rate': 0.07828556744059992, 'subsample': 0.5764184017745069, 'colsample_bytree': 0.637176841946562, 'min_child_weight': 7.0583909738564925, 'gamma': 2.233788789697428, 'reg_alpha': 0.22899014557393807, 'reg_lambda': 4.651507149029541}. Best is trial 19 with value: 0.6529026058349405.

Best trial: 19. Best value: 0.652903:  57%|█████▊    | 23/40 [00:43<00:40,  2.39s/it]

[I 2026-02-27 04:12:11,564] Trial 22 finished with value: 0.6453602098029702 and parameters: {'n_estimators': 361, 'max_depth': 5, 'learning_rate': 0.07179181405510075, 'subsample': 0.5832833116213719, 'colsample_bytree': 0.6347083777644205, 'min_child_weight': 6.330358826066122, 'gamma': 2.219079636043379, 'reg_alpha': 0.21418413328027355, 'reg_lambda': 4.685138091947127}. Best is trial 19 with value: 0.6529026058349405.

Best trial: 19. Best value: 0.652903:  60%|██████    | 24/40 [00:47<00:46,  2.92s/it]

[I 2026-02-27 04:12:15,738] Trial 23 finished with value: 0.6269226768592674 and parameters: {'n_estimators': 395, 'max_depth': 5, 'learning_rate': 0.04738618676422494, 'subsample': 0.6462309853675267, 'colsample_bytree': 0.6228175684838035, 'min_child_weight': 6.658038833736178, 'gamma': 2.177864496003765, 'reg_alpha': 0.23861324206439058, 'reg_lambda': 4.667829002145384}. Best is trial 19 with value: 0.6529026058349405.

Best trial: 24. Best value: 0.661249:  62%|██████▎   | 25/40 [00:52<00:52,  3.51s/it]

[I 2026-02-27 04:12:20,610] Trial 24 finished with value: 0.6612489853157196 and parameters: {'n_estimators': 372, 'max_depth': 5, 'learning_rate': 0.09532834521276065, 'subsample': 0.6877724080477418, 'colsample_bytree': 0.5817225873614031, 'min_child_weight': 6.153582673119448, 'gamma': 3.448116746210106, 'reg_alpha': 0.43662391732470807, 'reg_lambda': 3.83242813786797}. Best is trial 24 with value: 0.6612489853157196.

Best trial: 25. Best value: 0.663071:  65%|██████▌   | 26/40 [00:57<00:56,  4.04s/it]

[I 2026-02-27 04:12:25,892] Trial 25 finished with value: 0.6630705071798001 and parameters: {'n_estimators': 378, 'max_depth': 5, 'learning_rate': 0.09637541262545964, 'subsample': 0.7203744010873694, 'colsample_bytree': 0.5822054510896402, 'min_child_weight': 8.251041939542482, 'gamma': 3.560409468485683, 'reg_alpha': 0.4539343219146751, 'reg_lambda': 4.009730194960578}. Best is trial 25 with value: 0.6630705071798001.

Best trial: 25. Best value: 0.663071:  68%|██████▊   | 27/40 [01:01<00:54,  4.21s/it]

[I 2026-02-27 04:12:30,481] Trial 26 finished with value: 0.6161905814088979 and parameters: {'n_estimators': 380, 'max_depth': 4, 'learning_rate': 0.08608518045024083, 'subsample': 0.7174725360534133, 'colsample_bytree': 0.559540317570337, 'min_child_weight': 8.77159597252594, 'gamma': 3.5927113526243097, 'reg_alpha': 0.4650603057287869, 'reg_lambda': 3.731987192145259}. Best is trial 25 with value: 0.6630705071798001.

Best trial: 25. Best value: 0.663071:  70%|███████   | 28/40 [01:07<00:55,  4.64s/it]

[I 2026-02-27 04:12:36,148] Trial 27 finished with value: 0.6617064297552394 and parameters: {'n_estimators': 397, 'max_depth': 5, 'learning_rate': 0.09951932304517012, 'subsample': 0.7588427847081098, 'colsample_bytree': 0.5178855405794933, 'min_child_weight': 5.830007360191672, 'gamma': 4.32176483666564, 'reg_alpha': 0.6087644236248981, 'reg_lambda': 3.8627047906143344}. Best is trial 25 with value: 0.6630705071798001.

Best trial: 25. Best value: 0.663071:  72%|███████▎  | 29/40 [01:12<00:51,  4.71s/it]

[I 2026-02-27 04:12:40,999] Trial 28 finished with value: 0.6518312127784179 and parameters: {'n_estimators': 332, 'max_depth': 5, 'learning_rate': 0.09977386294455473, 'subsample': 0.7752809934084178, 'colsample_bytree': 0.5100181459614221, 'min_child_weight': 8.28713180891044, 'gamma': 4.3542180860955595, 'reg_alpha': 0.6577943523052092, 'reg_lambda': 3.8051865791355723}. Best is trial 25 with value: 0.6630705071798001.

Best trial: 25. Best value: 0.663071:  75%|███████▌  | 30/40 [01:17<00:48,  4.80s/it]

[I 2026-02-27 04:12:46,032] Trial 29 finished with value: 0.6569033913193102 and parameters: {'n_estimators': 321, 'max_depth': 5, 'learning_rate': 0.09936234165143673, 'subsample': 0.7517500046091605, 'colsample_bytree': 0.5500956588785839, 'min_child_weight': 5.52048099185088, 'gamma': 4.032008953437413, 'reg_alpha': 0.7311069242038647, 'reg_lambda': 4.046225877908799}. Best is trial 25 with value: 0.6630705071798001.

Best trial: 25. Best value: 0.663071:  78%|███████▊  | 31/40 [01:22<00:44,  4.90s/it]

[I 2026-02-27 04:12:51,160] Trial 30 finished with value: 0.559764807226166 and parameters: {'n_estimators': 375, 'max_depth': 4, 'learning_rate': 0.0424947047018604, 'subsample': 0.6977623947488522, 'colsample_bytree': 0.5086092075104098, 'min_child_weight': 14.72552667150615, 'gamma': 4.493744309693631, 'reg_alpha': 0.5591532486352594, 'reg_lambda': 3.284471456037328}. Best is trial 25 with value: 0.6630705071798001.

Best trial: 25. Best value: 0.663071:  80%|████████  | 32/40 [01:27<00:38,  4.80s/it]

[I 2026-02-27 04:12:55,738] Trial 31 finished with value: 0.6560857028538098 and parameters: {'n_estimators': 322, 'max_depth': 5, 'learning_rate': 0.09896269808910854, 'subsample': 0.7540920331500676, 'colsample_bytree': 0.5474520726624773, 'min_child_weight': 6.2500860969036935, 'gamma': 3.962984904960575, 'reg_alpha': 0.6067872505910327, 'reg_lambda': 3.963895285660754}. Best is trial 25 with value: 0.6630705071798001.

Best trial: 25. Best value: 0.663071:  82%|████████▎ | 33/40 [01:32<00:34,  4.98s/it]

[I 2026-02-27 04:13:01,135] Trial 32 finished with value: 0.6361652094462278 and parameters: {'n_estimators': 380, 'max_depth': 5, 'learning_rate': 0.05600597240724669, 'subsample': 0.7451000762047184, 'colsample_bytree': 0.5662092848297039, 'min_child_weight': 5.1945806990103, 'gamma': 3.778220706198781, 'reg_alpha': 0.4678105829584876, 'reg_lambda': 3.748931310183797}. Best is trial 25 with value: 0.6630705071798001.

Best trial: 25. Best value: 0.663071:  85%|████████▌ | 34/40 [01:37<00:30,  5.04s/it]

[I 2026-02-27 04:13:06,317] Trial 33 finished with value: 0.6571958545824303 and parameters: {'n_estimators': 364, 'max_depth': 5, 'learning_rate': 0.08922857195662366, 'subsample': 0.7190267679978525, 'colsample_bytree': 0.5311377183414109, 'min_child_weight': 7.5962033885782905, 'gamma': 4.102094324291324, 'reg_alpha': 0.687017056906122, 'reg_lambda': 3.4790868624375384}. Best is trial 25 with value: 0.6630705071798001.

Best trial: 25. Best value: 0.663071:  88%|████████▊ | 35/40 [01:42<00:25,  5.08s/it]

[I 2026-02-27 04:13:11,499] Trial 34 finished with value: 0.6427685899235354 and parameters: {'n_estimators': 366, 'max_depth': 5, 'learning_rate': 0.06797690350773752, 'subsample': 0.7251198188200445, 'colsample_bytree': 0.5314956294322648, 'min_child_weight': 9.122683494243304, 'gamma': 3.4166560221601525, 'reg_alpha': 0.7078738952935097, 'reg_lambda': 3.0985947810620114}. Best is trial 25 with value: 0.6630705071798001.

Best trial: 25. Best value: 0.663071:  90%|█████████ | 36/40 [01:48<00:20,  5.24s/it]

[I 2026-02-27 04:13:17,104] Trial 35 finished with value: 0.5068719954821785 and parameters: {'n_estimators': 386, 'max_depth': 5, 'learning_rate': 0.010498622167193059, 'subsample': 0.7077806897773921, 'colsample_bytree': 0.5915715987837686, 'min_child_weight': 10.927959125037752, 'gamma': 4.249896294261922, 'reg_alpha': 0.5951411143597025, 'reg_lambda': 3.4297810044604966}. Best is trial 25 with value: 0.6630705071798001.

Best trial: 25. Best value: 0.663071:  92%|█████████▎| 37/40 [01:53<00:15,  5.10s/it]

[I 2026-02-27 04:13:21,869] Trial 36 finished with value: 0.6481508828501472 and parameters: {'n_estimators': 350, 'max_depth': 5, 'learning_rate': 0.08948598859374658, 'subsample': 0.6724874732713151, 'colsample_bytree': 0.5199411120996044, 'min_child_weight': 7.812437889842992, 'gamma': 4.566164698845789, 'reg_alpha': 0.9635017155174935, 'reg_lambda': 3.5828614983460056}. Best is trial 25 with value: 0.6630705071798001.

Best trial: 25. Best value: 0.663071:  95%|█████████▌| 38/40 [01:59<00:10,  5.28s/it]

[I 2026-02-27 04:13:27,586] Trial 37 finished with value: 0.6471591387272578 and parameters: {'n_estimators': 400, 'max_depth': 5, 'learning_rate': 0.06897329254983421, 'subsample': 0.7684331929717092, 'colsample_bytree': 0.5681574663301177, 'min_child_weight': 10.570318470352696, 'gamma': 3.6748286772957446, 'reg_alpha': 0.8143686131626697, 'reg_lambda': 2.9552913146219666}. Best is trial 25 with value: 0.6630705071798001.

Best trial: 25. Best value: 0.663071:  98%|█████████▊| 39/40 [02:04<00:05,  5.23s/it]

[I 2026-02-27 04:13:32,676] Trial 38 finished with value: 0.6509217814387456 and parameters: {'n_estimators': 367, 'max_depth': 5, 'learning_rate': 0.08878799337052301, 'subsample': 0.6716783818406253, 'colsample_bytree': 0.6034586723622503, 'min_child_weight': 12.280690199848337, 'gamma': 3.3277343964930473, 'reg_alpha': 0.47483950292982935, 'reg_lambda': 4.295072758700008}. Best is trial 25 with value: 0.6630705071798001.

Best trial: 25. Best value: 0.663071: 100%|██████████| 40/40 [02:09<00:00,  3.24s/it]

[I 2026-02-27 04:13:38,236] Trial 39 finished with value: 0.6321711131119784 and parameters: {'n_estimators': 383, 'max_depth': 5, 'learning_rate': 0.05414775688449043, 'subsample': 0.7235942583897432, 'colsample_bytree': 0.5388300696095365, 'min_child_weight': 7.781939713479109, 'gamma': 3.971660674708979, 'reg_alpha': 0.859863281558424, 'reg_lambda': 3.8270556749289377}. Best is trial 25 with value: 0.6630705071798001.
Best CV R²: 0.6630705071798001
Best params:
  n_estimators: 378
  max_depth: 5
  learning_rate: 0.09637541262545964
  subsample: 0.7203744010873694
  colsample_bytree: 0.5822054510896402
  min_child_weight: 8.251041939542482
  gamma: 3.560409468485683
  reg_alpha: 0.4539343219146751
  reg_lambda: 4.009730194960578

In [7]:
# Train final TA model with best hyperparameters and report R² + feature importances

best_params = study.best_params.copy()
best_params.update({"random_state": 42, "n_jobs": -1})

final_model = xgb.XGBRegressor(**best_params)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

final_model.fit(
    X_train,
    y_train,
    eval_set=[(X_test, y_test)],
    verbose=False,
)

y_train_pred = final_model.predict(X_train)
y_test_pred = final_model.predict(X_test)

r2_train = r2_score(y_train, y_train_pred)
r2_test = r2_score(y_test, y_test_pred)

print(f"Final TA model Train R²: {r2_train:.3f}")
print(f"Final TA model Test  R²: {r2_test:.3f}")

importances = final_model.feature_importances_
fi_tuned = pd.DataFrame({"feature": feature_cols, "importance": importances})
fi_tuned = fi_tuned.sort_values("importance", ascending=False)

print("\nTop 20 most important features for predicting TA (tuned model):")
print(fi_tuned.head(20).to_string(index=False))

fi_tuned.head(20)

Final TA model Train R²: 0.868
Final TA model Test  R²: 0.658

Top 20 most important features for predicting TA (tuned model):
         feature  importance
            soil    0.135933
  esa_lccs_class    0.103266
             vpd    0.076838
             vap    0.063030
            tmin    0.060980
          swir16    0.048864
esa_change_count    0.048802
            NDMI    0.048567
           MNDWI    0.045058
             def    0.043363
             red    0.042916
             pet    0.041500
    month_fitted    0.040341
              ws    0.036080
             aet    0.034789
            pdsi    0.034302
            tmax    0.034138
             ppt    0.032384
               q    0.028850

             feature  importance
0               soil    0.135933
1     esa_lccs_class    0.103266
2                vpd    0.076838
3                vap    0.063030
6               tmin    0.060980
11            swir16    0.048864
4   esa_change_count    0.048802
9               NDMI    0.048567
5              MNDWI    0.045058
15               def    0.043363
13               red    0.042916
12               pet    0.041500
17      month_fitted    0.040341
10                ws    0.036080
16               aet    0.034789
8               pdsi    0.034302
14              tmax    0.034138
7                ppt    0.032384
18                 q    0.028850

In [8]:
# Create predictions for TA on validation data and update submission file

# Load current submission file (should have EC and DRP predictions already)
submission_path = "../../submission1.csv"
submission = pd.read_csv(submission_path)
print("Current submission shape:", submission.shape)
print("Submission columns:", list(submission.columns))

# VALIDATION CHECK: Ensure submission has exactly 200 rows
if submission.shape[0] != 200:
    print(f"\n⚠️  WARNING: Submission has {submission.shape[0]} rows instead of 200!")
    print("Loading fresh template instead...")
    submission = pd.read_csv("../../submission_template.csv")
    print(f"Loaded template with shape: {submission.shape}")

# Load validation features
val_features = pd.read_csv("../../New Datasets/Combined/Final Datasets/ta_validation.csv")
print("\nValidation dataset shape:", val_features.shape)
print("Validation columns:", list(val_features.columns))

# Build X_val using same TA feature set
X_val = val_features[feature_cols].copy()
print("\nValidation features shape:", X_val.shape)
print(f"Using {len(feature_cols)} features: {feature_cols[:5]}...")

# Predict TA for validation rows
ta_pred = final_model.predict(X_val)
print(f"\nGenerated {len(ta_pred)} TA predictions")
print(f"TA predictions - Min: {ta_pred.min():.2f}, Max: {ta_pred.max():.2f}, Mean: {ta_pred.mean():.2f}")

# CRITICAL: Match predictions to template by LAT/LON/DATE (not row order!)
val_features['TA_prediction'] = ta_pred

# Standardize column names for merge
val_features_std = val_features.rename(columns={
    'latitude': 'Latitude',
    'longitude': 'Longitude',
    'sample_date': 'Sample Date'
})

# Merge predictions with submission by coordinates AND date
submission_with_ta = submission.merge(
    val_features_std[['Latitude', 'Longitude', 'Sample Date', 'TA_prediction']],
    on=['Latitude', 'Longitude', 'Sample Date'],
    how='left'
)

# Update TA column
submission_with_ta['Total Alkalinity'] = submission_with_ta['TA_prediction']
submission_with_ta = submission_with_ta.drop(columns=['TA_prediction'])

# Ensure column order matches original
submission = submission_with_ta[submission.columns]

# VALIDATION CHECK: Ensure no missing predictions
missing_count = submission['Total Alkalinity'].isnull().sum()
if missing_count > 0:
    print(f"\n⚠️  WARNING: {missing_count} locations without TA predictions!")
    print("Missing locations:")
    print(submission[submission['Total Alkalinity'].isnull()][['Latitude', 'Longitude', 'Sample Date']].head(10))
else:
    print("\n✓ All 200 locations have TA predictions")

# Save final submission file
submission.to_csv(submission_path, index=False)
print(f"\nUpdated submission file: {submission_path}")
print("Submission shape:", submission.shape)
print("\n✓ All three water quality parameters predicted!")
print("\nFinal submission preview:")
submission.head()

Current submission shape: (200, 6)
Submission columns: ['Latitude', 'Longitude', 'Sample Date', 'Total Alkalinity', 'Electrical Conductance', 'Dissolved Reactive Phosphorus']

Validation dataset shape: (200, 24)
Validation columns: ['latitude', 'longitude', 'sample_date', 'month_fitted', 'swir16', 'swir22', 'red', 'NDMI', 'MNDWI', 'pet', 'aet', 'def', 'q', 'ppt', 'soil', 'srad', 'tmax', 'tmin', 'vap', 'vpd', 'ws', 'pdsi', 'esa_lccs_class', 'esa_change_count']

Validation features shape: (200, 19)
Using 19 features: ['soil', 'esa_lccs_class', 'vpd', 'vap', 'esa_change_count']...

Generated 200 TA predictions
TA predictions - Min: 1.44, Max: 193.50, Mean: 77.80

✓ All 200 locations have TA predictions

Updated submission file: ../../submission1.csv
Submission shape: (200, 6)

✓ All three water quality parameters predicted!

Final submission preview:

,Latitude,Longitude,Sample Date,Total Alkalinity,Electrical Conductance,Dissolved Reactive Phosphorus
0,-32.043333,27.822778,01-09-2014,81.448242,262.35413,NaN
1,-33.329167,26.077500,16-09-2015,96.677979,485.01056,NaN
2,-32.991639,27.640028,07-05-2015,50.423111,292.60873,NaN
3,-34.096389,24.439167,07-02-2012,73.046989,417.39285,NaN
4,-32.000556,28.581667,01-10-2014,46.272163,185.54149,NaN

In [9]:
df = pd.read_csv("../../submission1.csv")

# Put Longitude first, then Latitude, then keep the rest in the same order
cols = df.columns.tolist()
fixed_first = ["Longitude", "Latitude", "Sample Date"]
rest = [c for c in cols if c not in fixed_first]
df = df[fixed_first + rest]

df.to_csv("../../submission1.csv", index=False)