In [9]:
# Model1: XGBoost model to predict Dissolved Reactive Phosphorus (DRP)

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.metrics import r2_score

import optuna  # pip install optuna
import xgboost as xgb  # pip install xgboost

In [10]:
# Load DRP training dataset (features + target already joined)

data_path = "../../New Datasets/Combined/Final Datasets/drp_training_complete.csv"
full = pd.read_csv(data_path)

print("DRP Training dataset shape:", full.shape)
print("Columns:", list(full.columns))
full.head()

DRP Training dataset shape: (9319, 24)
Columns: ['latitude', 'longitude', 'month_fitted', 'swir16', 'swir22', 'red', 'NDMI', 'MNDWI', 'pet', 'aet', 'def', 'q', 'ppt', 'soil', 'srad', 'tmax', 'tmin', 'vap', 'vpd', 'ws', 'pdsi', 'esa_lccs_class', 'esa_change_count', 'dissolved_reactive_phosphorus']

,latitude,longitude,month_fitted,swir16,swir22,red,NDMI,MNDWI,pet,aet,...,srad,tmax,tmin,vap,vpd,ws,pdsi,esa_lccs_class,esa_change_count,dissolved_reactive_phosphorus
0,-34.405833,19.600556,42.031880,13580.000000,10717.000000,9095.500000,0.166424,-0.184320,132.300003,11.900001,...,263.801483,23.480000,12.179999,1.372,0.79,3.48,-2.59,120.0,0.0,15.962394
1,-34.405833,19.600556,38.341460,14055.575913,11746.892550,10363.898049,0.012617,-0.165667,70.400002,67.599998,...,158.596588,17.779999,7.240000,1.004,0.53,3.36,-3.30,120.0,0.0,7.812940
2,-34.405833,19.600556,53.145121,14090.844997,11846.217608,10413.610383,0.003518,-0.172979,163.000000,18.000000,...,323.498383,26.469999,15.740000,1.703,0.93,2.07,-3.49,120.0,0.0,12.787102
3,-34.405833,19.600556,38.539387,11536.500000,9401.000000,8631.000000,0.129337,-0.139379,51.400002,43.700001,...,113.603378,17.420000,8.400000,1.106,0.45,3.50,-1.60,120.0,0.0,2.278678
4,-34.405833,19.600556,39.406902,13263.500000,10589.000000,9197.500000,0.139460,-0.176520,88.200005,58.600002,...,195.097321,19.730000,10.200000,1.231,0.55,3.64,-1.40,120.0,0.0,18.831269

In [11]:
# Build feature matrix X and target y for DRP

# Columns to exclude from features
exclude_cols = {
    "dissolved_reactive_phosphorus",    # target
    "latitude", "longitude",            # spatial identifiers
}

base_feature_cols = [c for c in full.columns if c not in exclude_cols]
X_full = full[base_feature_cols].copy()
y = full["dissolved_reactive_phosphorus"]

print("Initial number of features:", len(base_feature_cols))
print("Features:", base_feature_cols)

# 1) Remove multicollinearity: drop one of each highly correlated pair
corr_matrix = X_full.corr().abs()
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))

high_corr_threshold = 0.95
cols_to_drop_mc = [col for col in upper.columns if any(upper[col] > high_corr_threshold)]

X_mc = X_full.drop(columns=cols_to_drop_mc)
feature_cols_mc = list(X_mc.columns)

print(f"Dropped {len(cols_to_drop_mc)} highly correlated features (>|{high_corr_threshold}|)")
print("Remaining features after multicollinearity reduction:", len(feature_cols_mc))

# Expose reduced set for feature selection
X_reduced_mc = X_mc.copy()
feature_cols_reduced_mc = feature_cols_mc

print("Example remaining feature columns:", feature_cols_reduced_mc[:10])

Initial number of features: 21
Features: ['month_fitted', 'swir16', 'swir22', 'red', 'NDMI', 'MNDWI', 'pet', 'aet', 'def', 'q', 'ppt', 'soil', 'srad', 'tmax', 'tmin', 'vap', 'vpd', 'ws', 'pdsi', 'esa_lccs_class', 'esa_change_count']
Dropped 2 highly correlated features (>|0.95|)
Remaining features after multicollinearity reduction: 19
Example remaining feature columns: ['month_fitted', 'swir16', 'red', 'NDMI', 'MNDWI', 'pet', 'aet', 'def', 'q', 'ppt']

In [12]:
# Feature selection via XGBoost feature importance (on multicollinearity-reduced set)

fs_model = xgb.XGBRegressor(
    n_estimators=400,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1,
)

fs_model.fit(X_reduced_mc, y)

importances = fs_model.feature_importances_
fi_fs = pd.DataFrame({"feature": feature_cols_reduced_mc, "importance": importances})
fi_fs = fi_fs.sort_values("importance", ascending=False).reset_index(drop=True)
fi_fs["cum_importance"] = fi_fs["importance"].cumsum()

# Keep features that explain up to 95% of total importance, but ensure at least 25 features
importance_cutoff = 0.90
min_features = 20
selected = fi_fs[fi_fs["cum_importance"] <= importance_cutoff]["feature"].tolist()
if len(selected) < min_features:
    selected = fi_fs.head(min_features)["feature"].tolist()

X = X_reduced_mc[selected].copy()
feature_cols = selected

print("Total features after multicollinearity reduction:", len(feature_cols_reduced_mc))
print("Selected features after importance-based selection:", len(feature_cols))
print("Top selected features:", feature_cols[:15])

Total features after multicollinearity reduction: 19
Selected features after importance-based selection: 19
Top selected features: ['esa_lccs_class', 'esa_change_count', 'soil', 'vpd', 'ppt', 'vap', 'pdsi', 'MNDWI', 'aet', 'tmax', 'ws', 'pet', 'tmin', 'def', 'q']

In [13]:
# Baseline XGBoost model (for quick R² and importances)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = xgb.XGBRegressor(
    n_estimators=400,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1,
)

model.fit(X_train, y_train)

y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

print(f"Baseline Train R²: {r2_score(y_train, y_train_pred):.3f}")
print(f"Baseline Test  R²: {r2_score(y_test, y_test_pred):.3f}")

importances_base = model.feature_importances_
fi_base = pd.DataFrame({"feature": feature_cols, "importance": importances_base})
fi_base.sort_values("importance", ascending=False).head(20)

Baseline Train R²: 0.849
Baseline Test  R²: 0.546

             feature  importance
0     esa_lccs_class    0.104601
1   esa_change_count    0.088124
2               soil    0.069501
15            swir16    0.060125
11               pet    0.057356
3                vpd    0.053081
7              MNDWI    0.048955
17               red    0.048902
12              tmin    0.046965
13               def    0.046341
8                aet    0.046266
16              NDMI    0.044534
6               pdsi    0.043990
5                vap    0.043862
9               tmax    0.043048
10                ws    0.042018
4                ppt    0.039821
14                 q    0.037402
18      month_fitted    0.035111

In [ ]:
# Stratified K-Fold + Optuna hyperparameter tuning for DRP model

n_bins = 10
y_strat = pd.qcut(y, q=n_bins, labels=False, duplicates='drop')

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

def objective(trial: optuna.trial.Trial) -> float:
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 200, 800),
        "max_depth": trial.suggest_int("max_depth", 3, 6),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
        "min_child_weight": trial.suggest_float("min_child_weight", 1.0, 10.0),
        "gamma": trial.suggest_float("gamma", 0.0, 5.0),
        "reg_alpha": trial.suggest_float("reg_alpha", 0.0, 1.0),
        "reg_lambda": trial.suggest_float("reg_lambda", 0.0, 2.0),
        "random_state": 42,
        "n_jobs": -1,
    }

    model = xgb.XGBRegressor(**params)

    cv_scores = []
    for train_idx, valid_idx in skf.split(X, y_strat):
        X_tr, X_val = X.iloc[train_idx], X.iloc[valid_idx]
        y_tr, y_val = y.iloc[train_idx], y.iloc[valid_idx]

        model.fit(X_tr, y_tr)
        y_val_pred = model.predict(X_val)
        cv_scores.append(r2_score(y_val, y_val_pred))

    return float(np.mean(cv_scores))

study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=40, show_progress_bar=True)

print("Best CV R²:", study.best_value)
print("Best params:")
for k, v in study.best_params.items():
    print(f"  {k}: {v}")

[I 2026-02-27 04:12:20,551] A new study created in memory with name: no-name-cc804c6d-a053-428a-9304-fee9657aba52
Best trial: 0. Best value: 0.529832:   2%|▎         | 1/40 [00:05<03:36,  5.55s/it]

[I 2026-02-27 04:12:26,101] Trial 0 finished with value: 0.5298322603597899 and parameters: {'n_estimators': 350, 'max_depth': 6, 'learning_rate': 0.11433121755899102, 'subsample': 0.5516552865442172, 'colsample_bytree': 0.6010145751806986, 'min_child_weight': 2.879630598482652, 'gamma': 4.8855177372498, 'reg_alpha': 0.10771238334338462, 'reg_lambda': 0.5854722414031328}. Best is trial 0 with value: 0.5298322603597899.

Best trial: 1. Best value: 0.53024:   5%|▌         | 2/40 [00:10<03:24,  5.38s/it]

[I 2026-02-27 04:12:31,364] Trial 1 finished with value: 0.5302404131777083 and parameters: {'n_estimators': 419, 'max_depth': 5, 'learning_rate': 0.25580625196755463, 'subsample': 0.9997543648211659, 'colsample_bytree': 0.7154962801281397, 'min_child_weight': 9.89071773778146, 'gamma': 0.7610353827017385, 'reg_alpha': 0.5742843090174999, 'reg_lambda': 0.2577090012671195}. Best is trial 1 with value: 0.5302404131777083.

Best trial: 1. Best value: 0.53024:   8%|▊         | 3/40 [00:13<02:26,  3.97s/it]

[I 2026-02-27 04:12:33,656] Trial 2 finished with value: 0.46179673246243463 and parameters: {'n_estimators': 204, 'max_depth': 4, 'learning_rate': 0.1577955847976257, 'subsample': 0.9920568248609709, 'colsample_bytree': 0.9131677583914761, 'min_child_weight': 2.249559548782104, 'gamma': 1.5745495578745743, 'reg_alpha': 0.6193808625562144, 'reg_lambda': 0.10850582242672258}. Best is trial 1 with value: 0.5302404131777083.

Best trial: 1. Best value: 0.53024:  10%|█         | 4/40 [00:17<02:31,  4.21s/it]

[I 2026-02-27 04:12:38,236] Trial 3 finished with value: 0.48216532731265127 and parameters: {'n_estimators': 384, 'max_depth': 5, 'learning_rate': 0.05117276415562891, 'subsample': 0.7225452928137428, 'colsample_bytree': 0.5249805760376342, 'min_child_weight': 1.0738938201941624, 'gamma': 0.883819767136787, 'reg_alpha': 0.3319666069967542, 'reg_lambda': 0.49960667858020136}. Best is trial 1 with value: 0.5302404131777083.

Best trial: 1. Best value: 0.53024:  12%|█▎        | 5/40 [00:20<02:12,  3.79s/it]

[I 2026-02-27 04:12:41,291] Trial 4 finished with value: 0.4365349653539101 and parameters: {'n_estimators': 380, 'max_depth': 3, 'learning_rate': 0.14963568055601884, 'subsample': 0.9658236505120408, 'colsample_bytree': 0.9158073057015728, 'min_child_weight': 2.331072308849321, 'gamma': 2.554028625027586, 'reg_alpha': 0.565931466966581, 'reg_lambda': 0.2661482327294964}. Best is trial 1 with value: 0.5302404131777083.

Best trial: 1. Best value: 0.53024:  15%|█▌        | 6/40 [00:28<02:51,  5.05s/it]

[I 2026-02-27 04:12:48,789] Trial 5 finished with value: 0.48726462980026175 and parameters: {'n_estimators': 635, 'max_depth': 4, 'learning_rate': 0.06879421037208368, 'subsample': 0.8471918031241767, 'colsample_bytree': 0.6382432373740949, 'min_child_weight': 6.617716449347684, 'gamma': 2.132783651823758, 'reg_alpha': 0.24832430103272796, 'reg_lambda': 0.16231407147812527}. Best is trial 1 with value: 0.5302404131777083.

Best trial: 1. Best value: 0.53024:  18%|█▊        | 7/40 [00:33<02:49,  5.15s/it]

[I 2026-02-27 04:12:54,140] Trial 6 finished with value: 0.4285397548424384 and parameters: {'n_estimators': 476, 'max_depth': 4, 'learning_rate': 0.04565586512625563, 'subsample': 0.5184177892640325, 'colsample_bytree': 0.5592989408523736, 'min_child_weight': 6.333118484630979, 'gamma': 4.864537375219829, 'reg_alpha': 0.5551573019268694, 'reg_lambda': 0.957371343590752}. Best is trial 1 with value: 0.5302404131777083.

Best trial: 1. Best value: 0.53024:  20%|██        | 8/40 [00:36<02:25,  4.55s/it]

[I 2026-02-27 04:12:57,388] Trial 7 finished with value: 0.4024252445799627 and parameters: {'n_estimators': 233, 'max_depth': 5, 'learning_rate': 0.03540573825568853, 'subsample': 0.8201799915658012, 'colsample_bytree': 0.5297081888013895, 'min_child_weight': 9.273674389724023, 'gamma': 3.7552926395517257, 'reg_alpha': 0.2667842426290792, 'reg_lambda': 0.9579983749825256}. Best is trial 1 with value: 0.5302404131777083.

Best trial: 1. Best value: 0.53024:  22%|██▎       | 9/40 [00:44<02:51,  5.54s/it]

[I 2026-02-27 04:13:05,123] Trial 8 finished with value: 0.36165738623064214 and parameters: {'n_estimators': 754, 'max_depth': 4, 'learning_rate': 0.012338404400521532, 'subsample': 0.6727858851363013, 'colsample_bytree': 0.513240462530421, 'min_child_weight': 7.771443825101842, 'gamma': 1.6854038884296474, 'reg_alpha': 0.7213412190952914, 'reg_lambda': 0.8789390918564632}. Best is trial 1 with value: 0.5302404131777083.

Best trial: 9. Best value: 0.534117:  25%|██▌       | 10/40 [00:50<02:46,  5.54s/it]

[I 2026-02-27 04:13:10,662] Trial 9 finished with value: 0.5341167322851271 and parameters: {'n_estimators': 370, 'max_depth': 6, 'learning_rate': 0.07020356854695507, 'subsample': 0.5108709445775538, 'colsample_bytree': 0.9492499105585158, 'min_child_weight': 6.175799912024195, 'gamma': 4.0164650111554066, 'reg_alpha': 0.3691643572229979, 'reg_lambda': 0.3502749771460494}. Best is trial 9 with value: 0.5341167322851271.

Best trial: 9. Best value: 0.534117:  28%|██▊       | 11/40 [00:59<03:11,  6.60s/it]

[I 2026-02-27 04:13:19,649] Trial 10 finished with value: 0.48901525399538254 and parameters: {'n_estimators': 592, 'max_depth': 6, 'learning_rate': 0.018330254855824617, 'subsample': 0.6176540106797729, 'colsample_bytree': 0.9827428678881003, 'min_child_weight': 4.609181879859056, 'gamma': 3.372552878028456, 'reg_alpha': 0.9806750667587266, 'reg_lambda': 1.7566765129499746}. Best is trial 9 with value: 0.5341167322851271.

Best trial: 9. Best value: 0.534117:  30%|███       | 12/40 [01:06<03:12,  6.87s/it]

[I 2026-02-27 04:13:27,131] Trial 11 finished with value: 0.528665264765892 and parameters: {'n_estimators': 494, 'max_depth': 6, 'learning_rate': 0.23956903410601207, 'subsample': 0.866809303094994, 'colsample_bytree': 0.7384752969186487, 'min_child_weight': 9.903537178191895, 'gamma': 0.24655939441803887, 'reg_alpha': 0.40507254190798836, 'reg_lambda': 1.3956655437740304}. Best is trial 9 with value: 0.5341167322851271.

Best trial: 9. Best value: 0.534117:  32%|███▎      | 13/40 [01:10<02:39,  5.91s/it]

[I 2026-02-27 04:13:30,845] Trial 12 finished with value: 0.5044954564388389 and parameters: {'n_estimators': 299, 'max_depth': 5, 'learning_rate': 0.2798551119860909, 'subsample': 0.7662284047242822, 'colsample_bytree': 0.7594559091575651, 'min_child_weight': 7.915130106109132, 'gamma': 3.492854652083906, 'reg_alpha': 0.7762519392423465, 'reg_lambda': 0.5197220830416562}. Best is trial 9 with value: 0.5341167322851271.

Best trial: 13. Best value: 0.552586:  35%|███▌      | 14/40 [01:17<02:42,  6.25s/it]

[I 2026-02-27 04:13:37,890] Trial 13 finished with value: 0.552586042009717 and parameters: {'n_estimators': 434, 'max_depth': 6, 'learning_rate': 0.08887474240481015, 'subsample': 0.9151046323002465, 'colsample_bytree': 0.7799899783099749, 'min_child_weight': 4.484336184411456, 'gamma': 0.137345761917551, 'reg_alpha': 0.03469183701659184, 'reg_lambda': 1.3242608144063466}. Best is trial 13 with value: 0.552586042009717.

Best trial: 14. Best value: 0.561576:  38%|███▊      | 15/40 [01:24<02:45,  6.61s/it]

[I 2026-02-27 04:13:45,325] Trial 14 finished with value: 0.5615764512266308 and parameters: {'n_estimators': 618, 'max_depth': 6, 'learning_rate': 0.09275242572190907, 'subsample': 0.8874194020221754, 'colsample_bytree': 0.8310888608515872, 'min_child_weight': 4.545755729011899, 'gamma': 4.150262193318169, 'reg_alpha': 0.013402859375056614, 'reg_lambda': 1.3839432786246564}. Best is trial 14 with value: 0.5615764512266308.

Best trial: 15. Best value: 0.565691:  40%|████      | 16/40 [01:31<02:36,  6.52s/it]

[I 2026-02-27 04:13:51,626] Trial 15 finished with value: 0.5656910466275321 and parameters: {'n_estimators': 596, 'max_depth': 6, 'learning_rate': 0.09890341647626939, 'subsample': 0.9131126793479161, 'colsample_bytree': 0.8338969825185163, 'min_child_weight': 4.341574389941717, 'gamma': 2.5438283252835943, 'reg_alpha': 0.05423097524316969, 'reg_lambda': 1.3178837361454763}. Best is trial 15 with value: 0.5656910466275321.

Best trial: 15. Best value: 0.565691:  42%|████▎     | 17/40 [01:34<02:08,  5.61s/it]

[I 2026-02-27 04:13:55,116] Trial 16 finished with value: 0.3532545129704882 and parameters: {'n_estimators': 615, 'max_depth': 3, 'learning_rate': 0.028913718696882425, 'subsample': 0.9036038437333265, 'colsample_bytree': 0.8408599518088596, 'min_child_weight': 4.070562829312182, 'gamma': 2.828779238897415, 'reg_alpha': 0.13204970845994818, 'reg_lambda': 1.9579053281934593}. Best is trial 15 with value: 0.5656910466275321.

Best trial: 15. Best value: 0.565691:  45%|████▌     | 18/40 [01:42<02:17,  6.26s/it]

[I 2026-02-27 04:14:02,892] Trial 17 finished with value: 0.5493847293194264 and parameters: {'n_estimators': 715, 'max_depth': 6, 'learning_rate': 0.11262835876243557, 'subsample': 0.8118266642817418, 'colsample_bytree': 0.8444253919692937, 'min_child_weight': 3.525057379546659, 'gamma': 4.202130923107835, 'reg_alpha': 0.14291109794192505, 'reg_lambda': 1.3426111783207406}. Best is trial 15 with value: 0.5656910466275321.

Best trial: 15. Best value: 0.565691:  48%|████▊     | 19/40 [01:48<02:10,  6.20s/it]

[I 2026-02-27 04:14:08,961] Trial 18 finished with value: 0.5470815067164219 and parameters: {'n_estimators': 682, 'max_depth': 5, 'learning_rate': 0.17652693170133768, 'subsample': 0.9335363154990254, 'colsample_bytree': 0.8362761918734923, 'min_child_weight': 5.307114371222261, 'gamma': 3.1466448436949266, 'reg_alpha': 0.0383568798109864, 'reg_lambda': 1.5349952766953123}. Best is trial 15 with value: 0.5656910466275321.

Best trial: 15. Best value: 0.565691:  50%|█████     | 20/40 [01:54<02:03,  6.16s/it]

[I 2026-02-27 04:14:15,009] Trial 19 finished with value: 0.5513023744886365 and parameters: {'n_estimators': 562, 'max_depth': 6, 'learning_rate': 0.09195100409164321, 'subsample': 0.7444526900773776, 'colsample_bytree': 0.6930536603016799, 'min_child_weight': 5.503292883891359, 'gamma': 4.396863437581192, 'reg_alpha': 0.19831945157575817, 'reg_lambda': 1.1597247100908665}. Best is trial 15 with value: 0.5656910466275321.

Best trial: 15. Best value: 0.565691:  52%|█████▎    | 21/40 [02:01<02:03,  6.50s/it]

[I 2026-02-27 04:14:22,326] Trial 20 finished with value: 0.5099134013714878 and parameters: {'n_estimators': 793, 'max_depth': 5, 'learning_rate': 0.029827566205938783, 'subsample': 0.8813574305971671, 'colsample_bytree': 0.8036604773677011, 'min_child_weight': 1.10506650467395, 'gamma': 2.0642082128307084, 'reg_alpha': 0.01688680107862306, 'reg_lambda': 1.6404503237126538}. Best is trial 15 with value: 0.5656910466275321.

Best trial: 15. Best value: 0.565691:  55%|█████▌    | 22/40 [02:08<01:55,  6.42s/it]

[I 2026-02-27 04:14:28,551] Trial 21 finished with value: 0.5535230954466681 and parameters: {'n_estimators': 542, 'max_depth': 6, 'learning_rate': 0.0829504498959177, 'subsample': 0.9280398272618061, 'colsample_bytree': 0.7871736720797514, 'min_child_weight': 4.568329202062427, 'gamma': 1.0346848415040175, 'reg_alpha': 0.020665236132900264, 'reg_lambda': 1.1952554971336586}. Best is trial 15 with value: 0.5656910466275321.

Best trial: 15. Best value: 0.565691:  57%|█████▊    | 23/40 [02:13<01:44,  6.14s/it]

[I 2026-02-27 04:14:34,030] Trial 22 finished with value: 0.5612881391652637 and parameters: {'n_estimators': 548, 'max_depth': 6, 'learning_rate': 0.077388438766539, 'subsample': 0.9355714189592581, 'colsample_bytree': 0.885964775677249, 'min_child_weight': 3.729659510346814, 'gamma': 0.9737556435089781, 'reg_alpha': 0.0008450825048644112, 'reg_lambda': 1.212243807892611}. Best is trial 15 with value: 0.5656910466275321.

Best trial: 15. Best value: 0.565691:  60%|██████    | 24/40 [02:18<01:31,  5.72s/it]

[I 2026-02-27 04:14:38,789] Trial 23 finished with value: 0.5573183356624292 and parameters: {'n_estimators': 654, 'max_depth': 6, 'learning_rate': 0.05816632032810545, 'subsample': 0.957002419449801, 'colsample_bytree': 0.8814147483783747, 'min_child_weight': 3.3706950674173184, 'gamma': 1.3767113941189306, 'reg_alpha': 0.13455224486652217, 'reg_lambda': 1.1219437438367144}. Best is trial 15 with value: 0.5656910466275321.

Best trial: 15. Best value: 0.565691:  62%|██████▎   | 25/40 [02:22<01:17,  5.18s/it]

[I 2026-02-27 04:14:42,687] Trial 24 finished with value: 0.5472693094259238 and parameters: {'n_estimators': 529, 'max_depth': 6, 'learning_rate': 0.12764225031891474, 'subsample': 0.7998549015354534, 'colsample_bytree': 0.8791532839654552, 'min_child_weight': 5.508214545130232, 'gamma': 2.93947907281435, 'reg_alpha': 0.2240189396739413, 'reg_lambda': 0.7942481152499162}. Best is trial 15 with value: 0.5656910466275321.

Best trial: 15. Best value: 0.565691:  65%|██████▌   | 26/40 [02:25<01:04,  4.63s/it]

[I 2026-02-27 04:14:46,028] Trial 25 finished with value: 0.531014278416377 and parameters: {'n_estimators': 574, 'max_depth': 5, 'learning_rate': 0.19762283185740565, 'subsample': 0.8530770847710827, 'colsample_bytree': 0.9822871750210213, 'min_child_weight': 3.718590563966982, 'gamma': 2.4321675990503566, 'reg_alpha': 0.43365999508213554, 'reg_lambda': 1.6141801159203975}. Best is trial 15 with value: 0.5656910466275321.

Best trial: 15. Best value: 0.565691:  68%|██████▊   | 27/40 [02:30<01:01,  4.77s/it]

[I 2026-02-27 04:14:51,125] Trial 26 finished with value: 0.5602758157839187 and parameters: {'n_estimators': 692, 'max_depth': 6, 'learning_rate': 0.04758371030792898, 'subsample': 0.8917625903926548, 'colsample_bytree': 0.8824979317870176, 'min_child_weight': 2.1646886537104177, 'gamma': 1.9555771616689381, 'reg_alpha': 0.09234691267241088, 'reg_lambda': 1.4557198227742738}. Best is trial 15 with value: 0.5656910466275321.

Best trial: 15. Best value: 0.565691:  70%|███████   | 28/40 [02:33<00:49,  4.13s/it]

[I 2026-02-27 04:14:53,766] Trial 27 finished with value: 0.5380471010965183 and parameters: {'n_estimators': 463, 'max_depth': 5, 'learning_rate': 0.09932066661453626, 'subsample': 0.9608865057318573, 'colsample_bytree': 0.8103936902463473, 'min_child_weight': 5.017772487219362, 'gamma': 0.404036974936574, 'reg_alpha': 0.30567047833058675, 'reg_lambda': 1.7888854520240263}. Best is trial 15 with value: 0.5656910466275321.

Best trial: 15. Best value: 0.565691:  72%|███████▎  | 29/40 [02:36<00:43,  3.93s/it]

[I 2026-02-27 04:14:57,243] Trial 28 finished with value: 0.5548519525065954 and parameters: {'n_estimators': 527, 'max_depth': 6, 'learning_rate': 0.06300086911759999, 'subsample': 0.7791677228564899, 'colsample_bytree': 0.683430447943721, 'min_child_weight': 2.9403967974060023, 'gamma': 1.2115578608981714, 'reg_alpha': 0.1900034830670528, 'reg_lambda': 1.24190977777735}. Best is trial 15 with value: 0.5656910466275321.

Best trial: 15. Best value: 0.565691:  75%|███████▌  | 30/40 [02:40<00:40,  4.01s/it]

[I 2026-02-27 04:15:01,434] Trial 29 finished with value: 0.5382427259854632 and parameters: {'n_estimators': 608, 'max_depth': 6, 'learning_rate': 0.13272535011289452, 'subsample': 0.7039280524416126, 'colsample_bytree': 0.9317093645302065, 'min_child_weight': 2.8821152214168064, 'gamma': 4.5969685055514145, 'reg_alpha': 0.08595204590676919, 'reg_lambda': 0.7254337161220226}. Best is trial 15 with value: 0.5656910466275321.

Best trial: 15. Best value: 0.565691:  78%|███████▊  | 31/40 [02:45<00:37,  4.14s/it]

[I 2026-02-27 04:15:05,867] Trial 30 finished with value: 0.5539200800432769 and parameters: {'n_estimators': 658, 'max_depth': 6, 'learning_rate': 0.10975334293511937, 'subsample': 0.8432050304188837, 'colsample_bytree': 0.8632857726705332, 'min_child_weight': 7.06092149824743, 'gamma': 3.7518416198091513, 'reg_alpha': 0.00027310398694277394, 'reg_lambda': 1.9914981417442006}. Best is trial 15 with value: 0.5656910466275321.

Best trial: 15. Best value: 0.565691:  80%|████████  | 32/40 [02:50<00:35,  4.44s/it]

[I 2026-02-27 04:15:11,029] Trial 31 finished with value: 0.5604213714188832 and parameters: {'n_estimators': 725, 'max_depth': 6, 'learning_rate': 0.04343292245124262, 'subsample': 0.8927384958773169, 'colsample_bytree': 0.8965320637957541, 'min_child_weight': 1.937195398688409, 'gamma': 1.9255974849381765, 'reg_alpha': 0.12076803638616507, 'reg_lambda': 1.4807383324289691}. Best is trial 15 with value: 0.5656910466275321.

In [ ]:
# Train final DRP model with best hyperparameters and report R² + feature importances

best_params = study.best_params.copy()
best_params.update({"random_state": 42, "n_jobs": -1})

final_model = xgb.XGBRegressor(**best_params)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

final_model.fit(X_train, y_train)

y_train_pred = final_model.predict(X_train)
y_test_pred = final_model.predict(X_test)

r2_train = r2_score(y_train, y_train_pred)
r2_test = r2_score(y_test, y_test_pred)

print(f"Final DRP model Train R²: {r2_train:.3f}")
print(f"Final DRP model Test  R²: {r2_test:.3f}")

importances = final_model.feature_importances_
fi_tuned = pd.DataFrame({"feature": feature_cols, "importance": importances})
fi_tuned = fi_tuned.sort_values("importance", ascending=False)

print("\nTop 20 most important features for predicting DRP (tuned model):")
print(fi_tuned.head(20).to_string(index=False))

fi_tuned.head(20)

Final DRP model Train R²: 0.924
Final DRP model Test  R²: 0.559

Top 20 most important features for predicting DRP (tuned model):
         feature  importance
esa_change_count    0.150877
  esa_lccs_class    0.133836
            soil    0.077050
             vpd    0.054722
          swir16    0.051673
           MNDWI    0.045696
             pet    0.045127
             def    0.040001
            pdsi    0.039621
             vap    0.038198
             red    0.038086
             ppt    0.038063
              ws    0.038001
            tmin    0.037903
            tmax    0.036635
               q    0.036632
            NDMI    0.034937
             aet    0.034758
    month_fitted    0.028183

             feature  importance
1   esa_change_count    0.150877
0     esa_lccs_class    0.133836
2               soil    0.077050
3                vpd    0.054722
15            swir16    0.051673
7              MNDWI    0.045696
11               pet    0.045127
13               def    0.040001
6               pdsi    0.039621
5                vap    0.038198
17               red    0.038086
4                ppt    0.038063
10                ws    0.038001
12              tmin    0.037903
9               tmax    0.036635
14                 q    0.036632
16              NDMI    0.034937
8                aet    0.034758
18      month_fitted    0.028183

In [ ]:
# Create predictions for DRP on validation data and update submission file

# Load current submission file (should have EC predictions already)
submission_path = "../../submission1.csv"
submission = pd.read_csv(submission_path)
print("Current submission shape:", submission.shape)
print("Submission columns:", list(submission.columns))

# VALIDATION CHECK: Ensure submission has exactly 200 rows
if submission.shape[0] != 200:
    print(f"\n⚠️  WARNING: Submission has {submission.shape[0]} rows instead of 200!")
    print("Loading fresh template instead...")
    submission = pd.read_csv("../../submission_template.csv")
    print(f"Loaded template with shape: {submission.shape}")

# Load validation features
val_features = pd.read_csv("../../New Datasets/Combined/Final Datasets/drp_validation.csv")
print("\nValidation dataset shape:", val_features.shape)
print("Validation columns:", list(val_features.columns))

# Build X_val using same DRP feature set
X_val = val_features[feature_cols].copy()
print("\nValidation features shape:", X_val.shape)
print(f"Using {len(feature_cols)} features: {feature_cols[:5]}...")

# Predict DRP for validation rows
drp_pred = final_model.predict(X_val)
print(f"\nGenerated {len(drp_pred)} DRP predictions")
print(f"DRP predictions - Min: {drp_pred.min():.2f}, Max: {drp_pred.max():.2f}, Mean: {drp_pred.mean():.2f}")

# CRITICAL: Match predictions to template by LAT/LON/DATE (not row order!)
val_features['DRP_prediction'] = drp_pred

# Standardize column names for merge
val_features_std = val_features.rename(columns={
    'latitude': 'Latitude',
    'longitude': 'Longitude',
    'sample_date': 'Sample Date'
})

# Merge predictions with submission by coordinates AND date
submission_with_drp = submission.merge(
    val_features_std[['Latitude', 'Longitude', 'Sample Date', 'DRP_prediction']],
    on=['Latitude', 'Longitude', 'Sample Date'],
    how='left'
)

# Update DRP column
submission_with_drp['Dissolved Reactive Phosphorus'] = submission_with_drp['DRP_prediction']
submission_with_drp = submission_with_drp.drop(columns=['DRP_prediction'])

# Ensure column order matches original
submission = submission_with_drp[submission.columns]

# VALIDATION CHECK: Ensure no missing predictions
missing_count = submission['Dissolved Reactive Phosphorus'].isnull().sum()
if missing_count > 0:
    print(f"\n⚠️  WARNING: {missing_count} locations without DRP predictions!")
    print("Missing locations:")
    print(submission[submission['Dissolved Reactive Phosphorus'].isnull()][['Latitude', 'Longitude', 'Sample Date']].head(10))
else:
    print("\n✓ All 200 locations have DRP predictions")

# Save updated submission file
submission.to_csv(submission_path, index=False)
print(f"\nUpdated submission file: {submission_path}")
print("Submission shape:", submission.shape)
print("\nFirst few rows of submission:")
submission.head()

Current submission shape: (200, 6)
Submission columns: ['Longitude', 'Latitude', 'Sample Date', 'Total Alkalinity', 'Electrical Conductance', 'Dissolved Reactive Phosphorus']

Validation dataset shape: (200, 23)
Validation columns: ['latitude', 'longitude', 'sample_date', 'swir16', 'swir22', 'red', 'NDMI', 'MNDWI', 'pet', 'aet', 'def', 'q', 'ppt', 'soil', 'srad', 'tmax', 'tmin', 'vap', 'vpd', 'ws', 'pdsi', 'esa_lccs_class', 'esa_change_count']

KeyError: "['month_fitted'] not in index"