In [26]:
# Model1: XGBoost model to predict Dissolved Reactive Phosphorus (DRP)

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.metrics import r2_score

import optuna  # pip install optuna
import xgboost as xgb  # pip install xgboost

In [27]:
# Load engineered training features and join with DRP target

features_path = "../New Datasets/Combined/combined_training_engineered.csv"
water_quality_path = "../Provided Datasets/water_quality_training_dataset.csv"

combined = pd.read_csv(features_path)
water_quality = pd.read_csv(water_quality_path)

# Standardize join keys to match `combined`
water_quality_std = water_quality.rename(
    columns={
        "Latitude": "latitude",
        "Longitude": "longitude",
        "Sample Date": "sample_date",
    }
)

# Keep only join keys + DRP target
drp_target = water_quality_std[["latitude", "longitude", "sample_date", "Dissolved Reactive Phosphorus"]]

# Inner join to align features with DRP labels
full = combined.merge(drp_target, on=["latitude", "longitude", "sample_date"], how="inner")

print("Features shape (combined):", combined.shape)
print("Water quality shape:", water_quality.shape)
print("Joined training shape:", full.shape)
full.head()

Features shape (combined): (9319, 82)
Water quality shape: (9319, 6)
Joined training shape: (9319, 83)

,latitude,longitude,sample_date,gaia_changed_ever_frac,gaia_impervious_frac_by_sample_year,gaia_recent_change_5y_frac,gaia_years_since_change_mean,gaia_transition_year_mean_changed_pixels,gsw_change,gsw_extent,...,hri,water_perm,water_instab,recurrence_ratio,seasonal_water,esa_change_intensity,wb_x_impervious,eci_x_impervious,gsw_occ_x_impervious,Dissolved Reactive Phosphorus
0,-34.405833,19.600556,01-10-2014,0.0,0.0,0.0,-1.0,-1.0,253.0,0.0,...,4703.580299,0.0,0.0,0.0,0,0.0,-0.0,0.0,0.0,20.0
1,-34.405833,19.600556,02-08-2011,0.0,0.0,0.0,-1.0,-1.0,253.0,0.0,...,1984.043203,0.0,0.0,0.0,0,0.0,-0.0,0.0,0.0,10.0
2,-34.405833,19.600556,02-12-2015,0.0,0.0,0.0,-1.0,-1.0,253.0,0.0,...,6827.433216,0.0,0.0,0.0,0,0.0,-0.0,0.0,0.0,20.0
3,-34.405833,19.600556,03-07-2013,0.0,0.0,0.0,-1.0,-1.0,253.0,0.0,...,1466.619596,0.0,0.0,0.0,0,0.0,-0.0,0.0,0.0,10.0
4,-34.405833,19.600556,03-09-2014,0.0,0.0,0.0,-1.0,-1.0,253.0,0.0,...,2919.631339,0.0,0.0,0.0,0,0.0,-0.0,0.0,0.0,20.0

In [28]:
# Build feature matrix X and target y for DRP, then reduce multicollinearity

# Columns to exclude from features
exclude_cols = {
    "Dissolved Reactive Phosphorus",    # target
    "Total Alkalinity",                 # do not include
    "Electrical Conductance",           # do not include
    "latitude", "longitude",           # do not include
    "sample_date",                      # string key, not a feature
}

base_feature_cols = [c for c in full.columns if c not in exclude_cols]
X_full = full[base_feature_cols].copy()
y = full["Dissolved Reactive Phosphorus"]

print("Initial number of features:", len(base_feature_cols))

# 1) Remove multicollinearity: drop one of each highly correlated pair
corr_matrix = X_full.corr().abs()
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))

high_corr_threshold = 0.95
cols_to_drop_mc = [col for col in upper.columns if any(upper[col] > high_corr_threshold)]

X_mc = X_full.drop(columns=cols_to_drop_mc)
feature_cols_mc = list(X_mc.columns)

print(f"Dropped {len(cols_to_drop_mc)} highly correlated features (>|{high_corr_threshold}|)")
print("Remaining features after multicollinearity reduction:", len(feature_cols_mc))

# Expose reduced set for feature selection
X_reduced_mc = X_mc.copy()
feature_cols_reduced_mc = feature_cols_mc

print("Example remaining feature columns:", feature_cols_reduced_mc[:10])

Initial number of features: 79
Dropped 24 highly correlated features (>|0.95|)
Remaining features after multicollinearity reduction: 55
Example remaining feature columns: ['gaia_changed_ever_frac', 'gaia_recent_change_5y_frac', 'gsw_change', 'gsw_occurrence', 'gsw_transitions', 'nir', 'green', 'swir16', 'NDMI', 'MNDWI']

In [29]:
# Feature selection via XGBoost feature importance (on multicollinearity-reduced set)

fs_model = xgb.XGBRegressor(
    n_estimators=400,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1,
)

fs_model.fit(X_reduced_mc, y)

importances = fs_model.feature_importances_
fi_fs = pd.DataFrame({"feature": feature_cols_reduced_mc, "importance": importances})
fi_fs = fi_fs.sort_values("importance", ascending=False).reset_index(drop=True)
fi_fs["cum_importance"] = fi_fs["importance"].cumsum()

# Keep features that explain up to 95% of total importance, but ensure at least 25 features
importance_cutoff = 0.90
min_features = 20
selected = fi_fs[fi_fs["cum_importance"] <= importance_cutoff]["feature"].tolist()
if len(selected) < min_features:
    selected = fi_fs.head(min_features)["feature"].tolist()

X = X_reduced_mc[selected].copy()
feature_cols = selected

print("Total features after multicollinearity reduction:", len(feature_cols_reduced_mc))
print("Selected features after importance-based selection:", len(feature_cols))
print("Top selected features:", feature_cols[:15])

Total features after multicollinearity reduction: 55
Selected features after importance-based selection: 31
Top selected features: ['esa_grass_frac_1km', 'esa_water_frac_1km', 'water_perm', 'esa_forest_frac_1km', 'gsw_recurrence_mean_1km', 'esa_shrub_frac_1km', 'gsw_occurrence_mean_1km', 'gaia_recent_change_5y_frac', 'gaia_changed_ever_frac_1km', 'esa_cropland_frac_1km', 'esa_urban_frac_1km', 'gaia_recent_change_5y_frac_1km', 'esa_other_frac_1km', 'recurrence_ratio', 'gsw_occ_x_impervious']

In [30]:
# Baseline XGBoost model (for quick R² and importances)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = xgb.XGBRegressor(
    n_estimators=400,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1,
)

model.fit(X_train, y_train)

y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

print(f"Baseline Train R²: {r2_score(y_train, y_train_pred):.3f}")
print(f"Baseline Test  R²: {r2_score(y_test, y_test_pred):.3f}")

importances_base = model.feature_importances_
fi_base = pd.DataFrame({"feature": feature_cols, "importance": importances_base})
fi_base.sort_values("importance", ascending=False).head(20)

Baseline Train R²: 0.903
Baseline Test  R²: 0.724

                           feature  importance
1               esa_water_frac_1km    0.143413
3              esa_forest_frac_1km    0.064680
0               esa_grass_frac_1km    0.057453
5               esa_shrub_frac_1km    0.056219
7       gaia_recent_change_5y_frac    0.056176
6          gsw_occurrence_mean_1km    0.055709
15                  esa_lccs_class    0.051167
8       gaia_changed_ever_frac_1km    0.047156
4          gsw_recurrence_mean_1km    0.042910
13                recurrence_ratio    0.040070
17          gaia_changed_ever_frac    0.039701
2                       water_perm    0.039182
9            esa_cropland_frac_1km    0.032796
12              esa_other_frac_1km    0.029329
11  gaia_recent_change_5y_frac_1km    0.029045
14            gsw_occ_x_impervious    0.024124
16                            soil    0.020005
21                eci_x_impervious    0.015655
20                           MNDWI    0.015330
10              esa_urban_frac_1km    0.014165

In [ ]:
# Stratified K-Fold + Optuna hyperparameter tuning for DRP model

n_bins = 10
y_strat = pd.qcut(y, q=n_bins, labels=False, duplicates='drop')

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

def objective(trial: optuna.trial.Trial) -> float:
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 200, 800),
        "max_depth": trial.suggest_int("max_depth", 3, 6),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
        "min_child_weight": trial.suggest_float("min_child_weight", 1.0, 10.0),
        "gamma": trial.suggest_float("gamma", 0.0, 5.0),
        "reg_alpha": trial.suggest_float("reg_alpha", 0.0, 1.0),
        "reg_lambda": trial.suggest_float("reg_lambda", 0.0, 2.0),
        "random_state": 42,
        "n_jobs": -1,
    }

    model = xgb.XGBRegressor(**params)

    cv_scores = []
    for train_idx, valid_idx in skf.split(X, y_strat):
        X_tr, X_val = X.iloc[train_idx], X.iloc[valid_idx]
        y_tr, y_val = y.iloc[train_idx], y.iloc[valid_idx]

        model.fit(X_tr, y_tr)
        y_val_pred = model.predict(X_val)
        cv_scores.append(r2_score(y_val, y_val_pred))

    return float(np.mean(cv_scores))

study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=40, show_progress_bar=True)

print("Best CV R²:", study.best_value)
print("Best params:")
for k, v in study.best_params.items():
    print(f"  {k}: {v}")

[I 2026-02-24 17:41:33,574] A new study created in memory with name: no-name-65310f30-2dc5-4a32-8993-702371caf761
Best trial: 0. Best value: 0.666166:   2%|▎         | 1/40 [00:01<01:06,  1.71s/it]

[I 2026-02-24 17:41:35,288] Trial 0 finished with value: 0.6661655639331145 and parameters: {'n_estimators': 263, 'max_depth': 5, 'learning_rate': 0.03407550409309202, 'subsample': 0.7781562521053547, 'colsample_bytree': 0.7430850345151654, 'min_child_weight': 3.4219380558559767, 'gamma': 3.461380491892721, 'reg_alpha': 0.7160943737810785, 'reg_lambda': 0.4903758097532358}. Best is trial 0 with value: 0.6661655639331145.

Best trial: 0. Best value: 0.666166:   5%|▌         | 2/40 [00:03<01:05,  1.73s/it]

[I 2026-02-24 17:41:37,038] Trial 1 finished with value: 0.5634361126499401 and parameters: {'n_estimators': 327, 'max_depth': 4, 'learning_rate': 0.010364157209664557, 'subsample': 0.8021775750645204, 'colsample_bytree': 0.6527740392819013, 'min_child_weight': 8.699997932011847, 'gamma': 1.4064682284854235, 'reg_alpha': 0.7415940959938586, 'reg_lambda': 0.9948669662666578}. Best is trial 0 with value: 0.6661655639331145.

Best trial: 2. Best value: 0.676859:   8%|▊         | 3/40 [00:04<01:00,  1.64s/it]

[I 2026-02-24 17:41:38,566] Trial 2 finished with value: 0.6768593609955464 and parameters: {'n_estimators': 235, 'max_depth': 5, 'learning_rate': 0.20662131102577488, 'subsample': 0.6956703819708911, 'colsample_bytree': 0.786351540343561, 'min_child_weight': 4.660171373246409, 'gamma': 2.8461791735092676, 'reg_alpha': 0.002306616708571463, 'reg_lambda': 0.9714136793387274}. Best is trial 2 with value: 0.6768593609955464.

Best trial: 3. Best value: 0.695655:  10%|█         | 4/40 [00:07<01:08,  1.91s/it]

[I 2026-02-24 17:41:40,879] Trial 3 finished with value: 0.6956547962052002 and parameters: {'n_estimators': 271, 'max_depth': 6, 'learning_rate': 0.044830067359054905, 'subsample': 0.989108639143506, 'colsample_bytree': 0.7192244170100359, 'min_child_weight': 3.982041611970128, 'gamma': 0.13209169715672542, 'reg_alpha': 0.9451133325945634, 'reg_lambda': 1.103105882942971}. Best is trial 3 with value: 0.6956547962052002.

Best trial: 3. Best value: 0.695655:  12%|█▎        | 5/40 [00:08<00:55,  1.60s/it]

[I 2026-02-24 17:41:41,929] Trial 4 finished with value: 0.4873741498893421 and parameters: {'n_estimators': 239, 'max_depth': 3, 'learning_rate': 0.01311219023399379, 'subsample': 0.9335168698330398, 'colsample_bytree': 0.7044567179022982, 'min_child_weight': 3.0179583644808976, 'gamma': 1.6422149964175026, 'reg_alpha': 0.6872269517146287, 'reg_lambda': 1.39880198313033}. Best is trial 3 with value: 0.6956547962052002.

Best trial: 3. Best value: 0.695655:  15%|█▌        | 6/40 [00:11<01:12,  2.14s/it]

[I 2026-02-24 17:41:45,108] Trial 5 finished with value: 0.608198810089682 and parameters: {'n_estimators': 580, 'max_depth': 4, 'learning_rate': 0.011352394030669547, 'subsample': 0.9040270165554803, 'colsample_bytree': 0.8907685239940608, 'min_child_weight': 4.176258756599499, 'gamma': 1.049243548825196, 'reg_alpha': 0.8227504725324727, 'reg_lambda': 1.761437488262287}. Best is trial 3 with value: 0.6956547962052002.

Best trial: 3. Best value: 0.695655:  18%|█▊        | 7/40 [00:12<01:00,  1.85s/it]

[I 2026-02-24 17:41:46,365] Trial 6 finished with value: 0.674654633029063 and parameters: {'n_estimators': 242, 'max_depth': 4, 'learning_rate': 0.12288543008306929, 'subsample': 0.7975971008201841, 'colsample_bytree': 0.8279138597451324, 'min_child_weight': 3.0158957510895457, 'gamma': 2.7634716901891543, 'reg_alpha': 0.968327397695074, 'reg_lambda': 0.5536199386314342}. Best is trial 3 with value: 0.6956547962052002.

Best trial: 3. Best value: 0.695655:  20%|██        | 8/40 [00:14<00:56,  1.75s/it]

[I 2026-02-24 17:41:47,906] Trial 7 finished with value: 0.58601680315803 and parameters: {'n_estimators': 304, 'max_depth': 4, 'learning_rate': 0.015603794170267173, 'subsample': 0.5236858153796884, 'colsample_bytree': 0.5747636734241368, 'min_child_weight': 3.788276098077361, 'gamma': 4.466740879896751, 'reg_alpha': 0.4683791320037407, 'reg_lambda': 0.02392238086332643}. Best is trial 3 with value: 0.6956547962052002.

Best trial: 3. Best value: 0.695655:  22%|██▎       | 9/40 [00:20<01:35,  3.07s/it]

[I 2026-02-24 17:41:53,882] Trial 8 finished with value: 0.5751571197784472 and parameters: {'n_estimators': 788, 'max_depth': 6, 'learning_rate': 0.28785054114072817, 'subsample': 0.504236492265973, 'colsample_bytree': 0.7937736257453589, 'min_child_weight': 5.48810542051893, 'gamma': 2.9223696783800857, 'reg_alpha': 0.5365966063490639, 'reg_lambda': 0.18499954367630544}. Best is trial 3 with value: 0.6956547962052002.

Best trial: 3. Best value: 0.695655:  25%|██▌       | 10/40 [00:23<01:31,  3.06s/it]

[I 2026-02-24 17:41:56,911] Trial 9 finished with value: 0.6875081627492277 and parameters: {'n_estimators': 611, 'max_depth': 4, 'learning_rate': 0.11834973422545207, 'subsample': 0.9218929200243919, 'colsample_bytree': 0.6553954625672223, 'min_child_weight': 3.5565776434480494, 'gamma': 3.5630427332066663, 'reg_alpha': 0.797313132931483, 'reg_lambda': 0.8224285184180096}. Best is trial 3 with value: 0.6956547962052002.

Best trial: 10. Best value: 0.700457:  28%|██▊       | 11/40 [00:26<01:31,  3.15s/it]

[I 2026-02-24 17:42:00,279] Trial 10 finished with value: 0.7004568779547495 and parameters: {'n_estimators': 454, 'max_depth': 6, 'learning_rate': 0.040001614162794165, 'subsample': 0.6382753437556947, 'colsample_bytree': 0.5174983921114825, 'min_child_weight': 1.149632053918236, 'gamma': 0.054083260591846316, 'reg_alpha': 0.24571313452297155, 'reg_lambda': 1.5017218365177305}. Best is trial 10 with value: 0.7004568779547495.

Best trial: 10. Best value: 0.700457:  30%|███       | 12/40 [00:29<01:28,  3.18s/it]

[I 2026-02-24 17:42:03,508] Trial 11 finished with value: 0.7003650734861198 and parameters: {'n_estimators': 425, 'max_depth': 6, 'learning_rate': 0.03846734367683853, 'subsample': 0.6467201061791551, 'colsample_bytree': 0.542106465924414, 'min_child_weight': 1.7125334894382735, 'gamma': 0.11667024594603274, 'reg_alpha': 0.20022634752792573, 'reg_lambda': 1.4924055718034996}. Best is trial 10 with value: 0.7004568779547495.

Best trial: 10. Best value: 0.700457:  32%|███▎      | 13/40 [00:33<01:26,  3.19s/it]

[I 2026-02-24 17:42:06,716] Trial 12 finished with value: 0.6902952388304573 and parameters: {'n_estimators': 428, 'max_depth': 6, 'learning_rate': 0.02584709366051106, 'subsample': 0.6356679781757704, 'colsample_bytree': 0.5211952558397109, 'min_child_weight': 1.0436311604039679, 'gamma': 0.020370033395744072, 'reg_alpha': 0.1723699472048193, 'reg_lambda': 1.9447461185807382}. Best is trial 10 with value: 0.7004568779547495.

Best trial: 10. Best value: 0.700457:  35%|███▌      | 14/40 [00:36<01:23,  3.20s/it]

[I 2026-02-24 17:42:09,934] Trial 13 finished with value: 0.6996752604429985 and parameters: {'n_estimators': 437, 'max_depth': 6, 'learning_rate': 0.06798611850914796, 'subsample': 0.6128987976120279, 'colsample_bytree': 0.5004775705073659, 'min_child_weight': 1.0133486880472207, 'gamma': 0.8002707795810523, 'reg_alpha': 0.29760705832283757, 'reg_lambda': 1.4607654920649813}. Best is trial 10 with value: 0.7004568779547495.

Best trial: 10. Best value: 0.700457:  38%|███▊      | 15/40 [00:39<01:19,  3.17s/it]

[I 2026-02-24 17:42:13,030] Trial 14 finished with value: 0.6906836247166845 and parameters: {'n_estimators': 512, 'max_depth': 5, 'learning_rate': 0.06733952079214173, 'subsample': 0.6021414497680255, 'colsample_bytree': 0.5918522425333294, 'min_child_weight': 7.284848155874152, 'gamma': 1.8947673769176707, 'reg_alpha': 0.24297662136797005, 'reg_lambda': 1.4966578310368104}. Best is trial 10 with value: 0.7004568779547495.

Best trial: 10. Best value: 0.700457:  40%|████      | 16/40 [00:42<01:17,  3.23s/it]

[I 2026-02-24 17:42:16,409] Trial 15 finished with value: 0.6936812873697179 and parameters: {'n_estimators': 408, 'max_depth': 6, 'learning_rate': 0.022647989948070726, 'subsample': 0.6902754847230654, 'colsample_bytree': 0.9806009560332765, 'min_child_weight': 2.0315697605376344, 'gamma': 0.7464640168340961, 'reg_alpha': 0.06813250706468432, 'reg_lambda': 1.6715171788148864}. Best is trial 10 with value: 0.7004568779547495.

Best trial: 10. Best value: 0.700457:  42%|████▎     | 17/40 [00:46<01:15,  3.28s/it]

[I 2026-02-24 17:42:19,803] Trial 16 finished with value: 0.6900352695341052 and parameters: {'n_estimators': 554, 'max_depth': 5, 'learning_rate': 0.047082413437680805, 'subsample': 0.7068587651101552, 'colsample_bytree': 0.5791142472106162, 'min_child_weight': 6.8098561003732385, 'gamma': 0.43242194639514087, 'reg_alpha': 0.3730132925750782, 'reg_lambda': 1.2394646862314176}. Best is trial 10 with value: 0.7004568779547495.

Best trial: 10. Best value: 0.700457:  45%|████▌     | 18/40 [00:48<01:08,  3.10s/it]

[I 2026-02-24 17:42:22,489] Trial 17 finished with value: 0.6610193862992586 and parameters: {'n_estimators': 690, 'max_depth': 3, 'learning_rate': 0.09455138465429343, 'subsample': 0.5564832187844452, 'colsample_bytree': 0.6377185650474962, 'min_child_weight': 2.067074826186486, 'gamma': 2.1524826744395944, 'reg_alpha': 0.13392667554035265, 'reg_lambda': 1.971741145079404}. Best is trial 10 with value: 0.7004568779547495.

Best trial: 10. Best value: 0.700457:  48%|████▊     | 19/40 [00:51<01:04,  3.07s/it]

[I 2026-02-24 17:42:25,475] Trial 18 finished with value: 0.6798957038880353 and parameters: {'n_estimators': 361, 'max_depth': 6, 'learning_rate': 0.02047780134848494, 'subsample': 0.6531628722085203, 'colsample_bytree': 0.5471161142782112, 'min_child_weight': 2.0299722425169997, 'gamma': 1.3283656959581158, 'reg_alpha': 0.4198465939162827, 'reg_lambda': 1.6561518700090367}. Best is trial 10 with value: 0.7004568779547495.

Best trial: 10. Best value: 0.700457:  50%|█████     | 20/40 [00:55<01:01,  3.09s/it]

[I 2026-02-24 17:42:28,626] Trial 19 finished with value: 0.6808418868715872 and parameters: {'n_estimators': 492, 'max_depth': 5, 'learning_rate': 0.038656453584776096, 'subsample': 0.5785718203774937, 'colsample_bytree': 0.6083216851340733, 'min_child_weight': 9.498921606891741, 'gamma': 0.541535060052594, 'reg_alpha': 0.28597914463706653, 'reg_lambda': 1.282878525275244}. Best is trial 10 with value: 0.7004568779547495.

Best trial: 20. Best value: 0.700953:  52%|█████▎    | 21/40 [00:59<01:08,  3.63s/it]

[I 2026-02-24 17:42:33,504] Trial 20 finished with value: 0.7009529500031791 and parameters: {'n_estimators': 658, 'max_depth': 6, 'learning_rate': 0.029587682102554268, 'subsample': 0.751412476417319, 'colsample_bytree': 0.5392917647682017, 'min_child_weight': 5.293409969369015, 'gamma': 0.0009689017978715686, 'reg_alpha': 0.5734640373703497, 'reg_lambda': 0.7848805350487273}. Best is trial 20 with value: 0.7009529500031791.

Best trial: 20. Best value: 0.700953:  55%|█████▌    | 22/40 [01:04<01:11,  3.95s/it]

[I 2026-02-24 17:42:38,212] Trial 21 finished with value: 0.7007229923132009 and parameters: {'n_estimators': 649, 'max_depth': 6, 'learning_rate': 0.029656697880315972, 'subsample': 0.7425966600350778, 'colsample_bytree': 0.5386981925105818, 'min_child_weight': 6.741844897201094, 'gamma': 0.049616067426252006, 'reg_alpha': 0.5658517052730597, 'reg_lambda': 0.6886806860007137}. Best is trial 20 with value: 0.7009529500031791.

Best trial: 20. Best value: 0.700953:  57%|█████▊    | 23/40 [01:09<01:10,  4.17s/it]

[I 2026-02-24 17:42:42,884] Trial 22 finished with value: 0.7006365179056082 and parameters: {'n_estimators': 657, 'max_depth': 6, 'learning_rate': 0.024233270321246635, 'subsample': 0.844600435430281, 'colsample_bytree': 0.5248072369878051, 'min_child_weight': 6.6244718603167705, 'gamma': 1.07523132375272, 'reg_alpha': 0.586484910131507, 'reg_lambda': 0.7118008146868346}. Best is trial 20 with value: 0.7009529500031791.

Best trial: 20. Best value: 0.700953:  60%|██████    | 24/40 [01:13<01:06,  4.17s/it]

[I 2026-02-24 17:42:47,062] Trial 23 finished with value: 0.6868851035625617 and parameters: {'n_estimators': 686, 'max_depth': 5, 'learning_rate': 0.027346264454050723, 'subsample': 0.8681510187007594, 'colsample_bytree': 0.6250026222123446, 'min_child_weight': 6.874610887418575, 'gamma': 1.0059507076063041, 'reg_alpha': 0.5912599905862731, 'reg_lambda': 0.6818664582334014}. Best is trial 20 with value: 0.7009529500031791.

Best trial: 20. Best value: 0.700953:  62%|██████▎   | 25/40 [01:18<01:06,  4.42s/it]

[I 2026-02-24 17:42:52,072] Trial 24 finished with value: 0.6930692332803065 and parameters: {'n_estimators': 677, 'max_depth': 6, 'learning_rate': 0.014951838636400825, 'subsample': 0.8547077888948883, 'colsample_bytree': 0.6739690680783739, 'min_child_weight': 6.081579304976926, 'gamma': 0.5806356389653222, 'reg_alpha': 0.6056160988641871, 'reg_lambda': 0.3238904117402046}. Best is trial 20 with value: 0.7009529500031791.

Best trial: 20. Best value: 0.700953:  65%|██████▌   | 26/40 [01:24<01:07,  4.82s/it]

[I 2026-02-24 17:42:57,802] Trial 25 finished with value: 0.6963784433202522 and parameters: {'n_estimators': 777, 'max_depth': 6, 'learning_rate': 0.01843431574791646, 'subsample': 0.743648847402121, 'colsample_bytree': 0.5494465022879835, 'min_child_weight': 7.903806193592788, 'gamma': 1.282656769739654, 'reg_alpha': 0.6189027934957942, 'reg_lambda': 0.7891383514451412}. Best is trial 20 with value: 0.7009529500031791.

Best trial: 20. Best value: 0.700953:  68%|██████▊   | 27/40 [01:28<00:58,  4.52s/it]

[I 2026-02-24 17:43:01,648] Trial 26 finished with value: 0.6875220496365394 and parameters: {'n_estimators': 628, 'max_depth': 5, 'learning_rate': 0.029390778822528853, 'subsample': 0.8351634083670301, 'colsample_bytree': 0.5789625585583447, 'min_child_weight': 5.301273696321545, 'gamma': 0.48550402235224005, 'reg_alpha': 0.49988390849298037, 'reg_lambda': 0.4783507604397451}. Best is trial 20 with value: 0.7009529500031791.

In [ ]:
# Train final DRP model with best hyperparameters and report R² + feature importances

best_params = study.best_params.copy()
best_params.update({"random_state": 42, "n_jobs": -1})

final_model = xgb.XGBRegressor(**best_params)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

final_model.fit(X_train, y_train)

y_train_pred = final_model.predict(X_train)
y_test_pred = final_model.predict(X_test)

r2_train = r2_score(y_train, y_train_pred)
r2_test = r2_score(y_test, y_test_pred)

print(f"Final DRP model Train R²: {r2_train:.3f}")
print(f"Final DRP model Test  R²: {r2_test:.3f}")

importances = final_model.feature_importances_
fi_tuned = pd.DataFrame({"feature": feature_cols, "importance": importances})
fi_tuned = fi_tuned.sort_values("importance", ascending=False)

print("\nTop 20 most important features for predicting DRP (tuned model):")
print(fi_tuned.head(20).to_string(index=False))

fi_tuned.head(20)

Final DRP model Train R²: 0.889
Final DRP model Test  R²: 0.721

Top 20 most important features for predicting DRP (tuned model):
                       feature  importance
            esa_water_frac_1km    0.155634
            esa_grass_frac_1km    0.081081
       gsw_occurrence_mean_1km    0.067563
           esa_forest_frac_1km    0.065639
            esa_shrub_frac_1km    0.063249
    gaia_recent_change_5y_frac    0.056431
                esa_lccs_class    0.049961
    gaia_changed_ever_frac_1km    0.045247
       gsw_recurrence_mean_1km    0.041032
         esa_cropland_frac_1km    0.038343
                    water_perm    0.033285
gaia_recent_change_5y_frac_1km    0.030975
        gaia_changed_ever_frac    0.030496
              recurrence_ratio    0.029384
            esa_other_frac_1km    0.026016
          gsw_occ_x_impervious    0.024611
            esa_urban_frac_1km    0.020132
                          soil    0.016008
                         MNDWI    0.012778
               wb_x_impervious    0.012707

                           feature  importance
1               esa_water_frac_1km    0.155634
0               esa_grass_frac_1km    0.081081
6          gsw_occurrence_mean_1km    0.067563
3              esa_forest_frac_1km    0.065639
5               esa_shrub_frac_1km    0.063249
7       gaia_recent_change_5y_frac    0.056431
15                  esa_lccs_class    0.049961
8       gaia_changed_ever_frac_1km    0.045247
4          gsw_recurrence_mean_1km    0.041032
9            esa_cropland_frac_1km    0.038343
2                       water_perm    0.033285
11  gaia_recent_change_5y_frac_1km    0.030975
17          gaia_changed_ever_frac    0.030496
13                recurrence_ratio    0.029384
12              esa_other_frac_1km    0.026016
14            gsw_occ_x_impervious    0.024611
10              esa_urban_frac_1km    0.020132
16                            soil    0.016008
20                           MNDWI    0.012778
18                 wb_x_impervious    0.012707

In [ ]:
# Predict DRP for validation rows and overwrite DRP column in submission1.csv

# Load submission1.csv (with EC/TA predictions) and validation engineered features
submission_path = "../submission1.csv"
submission = pd.read_csv(submission_path)
val_features = pd.read_csv("../New Datasets/Combined/combined_validation_engineered.csv")

# Standardize keys in submission to match engineered features
sub_std = submission.rename(columns={
    "Latitude": "latitude",
    "Longitude": "longitude",
    "Sample Date": "sample_date",
})

# Join validation features with submission IDs
val_full = val_features.merge(
    sub_std[["latitude", "longitude", "sample_date"]],
    on=["latitude", "longitude", "sample_date"],
    how="inner",
)

print("Validation rows with matched features (DRP):", val_full.shape[0])

# Build X_val using same DRP feature set
X_val = val_full[feature_cols].copy()

drp_pred = final_model.predict(X_val)

# Map predictions back into submission
pred_df = val_full[["latitude", "longitude", "sample_date"]].copy()
pred_df["Dissolved Reactive Phosphorus"] = drp_pred
pred_df = pred_df.rename(columns={
    "latitude": "Latitude",
    "longitude": "Longitude",
    "sample_date": "Sample Date",
})

submission = submission.drop(columns=["Dissolved Reactive Phosphorus"]).merge(
    pred_df,
    on=["Latitude", "Longitude", "Sample Date"],
    how="left",
)

submission.to_csv(submission_path, index=False)
print("Updated submission1.csv with Dissolved Reactive Phosphorus predictions.")
submission.head()

Validation rows with matched features (DRP): 200
Updated submission1.csv with Dissolved Reactive Phosphorus predictions.

,Longitude,Latitude,Sample Date,Electrical Conductance,Total Alkalinity,Dissolved Reactive Phosphorus
0,27.822778,-32.043333,01-09-2014,469.42007,152.837880,46.209438
1,26.077500,-33.329167,16-09-2015,161.70978,31.439138,13.076386
2,27.640028,-32.991639,07-05-2015,221.35207,41.791824,18.486393
3,24.439167,-34.096389,07-02-2012,343.66388,44.698444,13.726166
4,28.581667,-32.000556,01-10-2014,530.69940,106.132515,22.970081