In [9]:
# Model1: XGBoost model to predict Electrical Conductance (EC)

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.metrics import r2_score

import optuna  # pip install optuna
# XGBoost (install first if needed: `pip install xgboost`)
import xgboost as xgb

In [10]:
# Load engineered training features and join with EC target

features_path = "../New Datasets/Combined/combined_training_engineered.csv"
water_quality_path = "../Provided Datasets/water_quality_training_dataset.csv"

combined = pd.read_csv(features_path)
water_quality = pd.read_csv(water_quality_path)

# Standardize join keys to match `combined`
water_quality_std = water_quality.rename(
    columns={
        "Latitude": "latitude",
        "Longitude": "longitude",
        "Sample Date": "sample_date",
    }
)

# Keep only join keys + EC target
ec_target = water_quality_std[["latitude", "longitude", "sample_date", "Electrical Conductance"]]

# Inner join to align features with EC labels
full = combined.merge(ec_target, on=["latitude", "longitude", "sample_date"], how="inner")

print("Features shape (combined):", combined.shape)
print("Water quality shape:", water_quality.shape)
print("Joined training shape:", full.shape)
full.head()

Features shape (combined): (9319, 82)
Water quality shape: (9319, 6)
Joined training shape: (9319, 83)

,latitude,longitude,sample_date,gaia_changed_ever_frac,gaia_impervious_frac_by_sample_year,gaia_recent_change_5y_frac,gaia_years_since_change_mean,gaia_transition_year_mean_changed_pixels,gsw_change,gsw_extent,...,hri,water_perm,water_instab,recurrence_ratio,seasonal_water,esa_change_intensity,wb_x_impervious,eci_x_impervious,gsw_occ_x_impervious,Electrical Conductance
0,-34.405833,19.600556,01-10-2014,0.0,0.0,0.0,-1.0,-1.0,253.0,0.0,...,4703.580299,0.0,0.0,0.0,0,0.0,-0.0,0.0,0.0,1008.0
1,-34.405833,19.600556,02-08-2011,0.0,0.0,0.0,-1.0,-1.0,253.0,0.0,...,1984.043203,0.0,0.0,0.0,0,0.0,-0.0,0.0,0.0,1237.0
2,-34.405833,19.600556,02-12-2015,0.0,0.0,0.0,-1.0,-1.0,253.0,0.0,...,6827.433216,0.0,0.0,0.0,0,0.0,-0.0,0.0,0.0,1053.0
3,-34.405833,19.600556,03-07-2013,0.0,0.0,0.0,-1.0,-1.0,253.0,0.0,...,1466.619596,0.0,0.0,0.0,0,0.0,-0.0,0.0,0.0,1167.0
4,-34.405833,19.600556,03-09-2014,0.0,0.0,0.0,-1.0,-1.0,253.0,0.0,...,2919.631339,0.0,0.0,0.0,0,0.0,-0.0,0.0,0.0,877.0

In [11]:
# Build feature matrix X and target y for EC, then reduce multicollinearity

# Columns to exclude from features
exclude_cols = {
    "Electrical Conductance",            # target
    "Total Alkalinity",                 # do not include
    "Dissolved Reactive Phosphorus",    # do not include
    "latitude", "longitude",           # do not include
    "sample_date",                      # string key, not a feature
}

base_feature_cols = [c for c in full.columns if c not in exclude_cols]
X_full = full[base_feature_cols].copy()
y = full["Electrical Conductance"]

print("Initial number of features:", len(base_feature_cols))

# 1) Remove multicollinearity: drop one of each highly correlated pair
corr_matrix = X_full.corr().abs()
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))

high_corr_threshold = 0.95
cols_to_drop_mc = [col for col in upper.columns if any(upper[col] > high_corr_threshold)]

X_mc = X_full.drop(columns=cols_to_drop_mc)
feature_cols_mc = list(X_mc.columns)

print(f"Dropped {len(cols_to_drop_mc)} highly correlated features (>|{high_corr_threshold}|)")
print("Remaining features after multicollinearity reduction:", len(feature_cols_mc))

# For downstream cells we will further reduce by feature importance, then set X and feature_cols there.
# For now, expose X_mc and feature_cols_mc
X_reduced_mc = X_mc.copy()
feature_cols_reduced_mc = feature_cols_mc

print("Example remaining feature columns:", feature_cols_reduced_mc[:10])

Initial number of features: 79
Dropped 24 highly correlated features (>|0.95|)
Remaining features after multicollinearity reduction: 55
Example remaining feature columns: ['gaia_changed_ever_frac', 'gaia_recent_change_5y_frac', 'gsw_change', 'gsw_occurrence', 'gsw_transitions', 'nir', 'green', 'swir16', 'NDMI', 'MNDWI']

In [12]:
# Feature selection via XGBoost feature importance (on multicollinearity-reduced set)

# Use a reasonably strong but not overfitted model to rank features
fs_model = xgb.XGBRegressor(
    n_estimators=400,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1,
)

fs_model.fit(X_reduced_mc, y)

importances = fs_model.feature_importances_
fi_fs = pd.DataFrame({"feature": feature_cols_reduced_mc, "importance": importances})
fi_fs = fi_fs.sort_values("importance", ascending=False).reset_index(drop=True)
fi_fs["cum_importance"] = fi_fs["importance"].cumsum()

# Keep features that explain up to 90% of total importance, but ensure at least 20 features
importance_cutoff = 0.90
min_features = 20
selected = fi_fs[fi_fs["cum_importance"] <= importance_cutoff]["feature"].tolist()
if len(selected) < min_features:
    selected = fi_fs.head(min_features)["feature"].tolist()

X = X_reduced_mc[selected].copy()
feature_cols = selected

print("Total features after multicollinearity reduction:", len(feature_cols_reduced_mc))
print("Selected features after importance-based selection:", len(feature_cols))
print("Top selected features:", feature_cols[:15])

Total features after multicollinearity reduction: 55
Selected features after importance-based selection: 26
Top selected features: ['esa_flooded_frac_1km', 'esa_sparse_veg_frac_1km', 'esa_forest_frac_1km', 'esa_grass_frac_1km', 'water_perm', 'recurrence_ratio', 'gsw_recurrence_mean_1km', 'esa_other_frac_1km', 'esa_lccs_class', 'esa_water_frac_1km', 'gsw_occurrence_mean_1km', 'soil', 'gsw_transitions', 'gaia_changed_ever_frac_1km', 'esa_change_count']

In [13]:
# Train XGBoost model and report R² + feature importances

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = xgb.XGBRegressor(
    n_estimators=400,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1,
)

model.fit(X_train, y_train)

# R² scores
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

r2_train = r2_score(y_train, y_train_pred)
r2_test = r2_score(y_test, y_test_pred)

print(f"Train R²: {r2_train:.3f}")
print(f"Test  R²: {r2_test:.3f}")

# Feature importances
importances = model.feature_importances_
fi = pd.DataFrame({"feature": feature_cols, "importance": importances})
fi = fi.sort_values("importance", ascending=False)

print("\nTop 20 most important features for predicting EC:")
print(fi.head(20).to_string(index=False))

fi.head(20)

Train R²: 0.941
Test  R²: 0.855

Top 20 most important features for predicting EC:
                   feature  importance
        esa_water_frac_1km    0.080212
   gsw_recurrence_mean_1km    0.064581
            esa_lccs_class    0.060999
   gsw_occurrence_mean_1km    0.060504
      esa_flooded_frac_1km    0.057803
                water_perm    0.054374
        esa_grass_frac_1km    0.054277
          recurrence_ratio    0.053385
       esa_forest_frac_1km    0.052938
        esa_other_frac_1km    0.052868
          esa_change_count    0.045377
     esa_cropland_frac_1km    0.044679
        esa_shrub_frac_1km    0.042649
   esa_sparse_veg_frac_1km    0.038886
                      soil    0.032614
        esa_urban_frac_1km    0.032605
           gsw_transitions    0.029880
    gaia_changed_ever_frac    0.026151
                gsw_change    0.025526
gaia_changed_ever_frac_1km    0.024373

                       feature  importance
9           esa_water_frac_1km    0.080212
6      gsw_recurrence_mean_1km    0.064581
8               esa_lccs_class    0.060999
10     gsw_occurrence_mean_1km    0.060504
0         esa_flooded_frac_1km    0.057803
4                   water_perm    0.054374
3           esa_grass_frac_1km    0.054277
5             recurrence_ratio    0.053385
2          esa_forest_frac_1km    0.052938
7           esa_other_frac_1km    0.052868
14            esa_change_count    0.045377
17       esa_cropland_frac_1km    0.044679
15          esa_shrub_frac_1km    0.042649
1      esa_sparse_veg_frac_1km    0.038886
11                        soil    0.032614
16          esa_urban_frac_1km    0.032605
12             gsw_transitions    0.029880
23      gaia_changed_ever_frac    0.026151
25                  gsw_change    0.025526
13  gaia_changed_ever_frac_1km    0.024373

In [14]:
# Stratified K-Fold + Optuna hyperparameter tuning for EC model

# Bin the continuous target into quantiles for stratification
n_bins = 10
# qcut can have duplicate bin edges; drop duplicates
y_strat = pd.qcut(y, q=n_bins, labels=False, duplicates='drop')

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

def objective(trial: optuna.trial.Trial) -> float:
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 200, 400),
        "max_depth": trial.suggest_int("max_depth", 3, 5),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.1, log=True),
        "subsample": trial.suggest_float("subsample", 0.5, 0.8),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 0.8),
        "min_child_weight": trial.suggest_float("min_child_weight", 5.0, 20.0),
        "gamma": trial.suggest_float("gamma", 0.5, 5.0),
        "reg_alpha": trial.suggest_float("reg_alpha", 0.0, 1.0),
        "reg_lambda": trial.suggest_float("reg_lambda", 1.0, 5.0),
        "random_state": 42,
        "n_jobs": -1,
    }

    model = xgb.XGBRegressor(**params)

    cv_scores = []
    for train_idx, valid_idx in skf.split(X, y_strat):
        X_tr, X_val = X.iloc[train_idx], X.iloc[valid_idx]
        y_tr, y_val = y.iloc[train_idx], y.iloc[valid_idx]

        model.fit(
            X_tr,
            y_tr,
            eval_set=[(X_val, y_val)],
            verbose=False,
        )
        y_val_pred = model.predict(X_val)
        cv_scores.append(r2_score(y_val, y_val_pred))

    return float(np.mean(cv_scores))

study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=40, show_progress_bar=True)

print("Best CV R²:", study.best_value)
print("Best params:")
for k, v in study.best_params.items():
    print(f"  {k}: {v}")

[I 2026-02-24 17:36:41,498] A new study created in memory with name: no-name-843eb4b8-cf56-4c3f-8072-8e9f53575f09
Best trial: 0. Best value: 0.707191:   2%|▎         | 1/40 [00:02<01:51,  2.87s/it]

[I 2026-02-24 17:36:44,369] Trial 0 finished with value: 0.7071906599028042 and parameters: {'n_estimators': 224, 'max_depth': 4, 'learning_rate': 0.018958661309646543, 'subsample': 0.795379055898638, 'colsample_bytree': 0.5655743440464263, 'min_child_weight': 16.495927307543862, 'gamma': 1.9563627600334774, 'reg_alpha': 0.4536588256416999, 'reg_lambda': 3.1562572831889786}. Best is trial 0 with value: 0.7071906599028042.

Best trial: 1. Best value: 0.778052:   5%|▌         | 2/40 [00:05<01:47,  2.83s/it]

[I 2026-02-24 17:36:47,174] Trial 1 finished with value: 0.7780524169626304 and parameters: {'n_estimators': 223, 'max_depth': 4, 'learning_rate': 0.03612644006279968, 'subsample': 0.6740314847809434, 'colsample_bytree': 0.5711654906433691, 'min_child_weight': 6.550384254076905, 'gamma': 3.9133879882287705, 'reg_alpha': 0.6886057268070482, 'reg_lambda': 4.317127898502302}. Best is trial 1 with value: 0.7780524169626304.

Best trial: 2. Best value: 0.837082:   8%|▊         | 3/40 [00:10<02:22,  3.85s/it]

[I 2026-02-24 17:36:52,233] Trial 2 finished with value: 0.8370820714994724 and parameters: {'n_estimators': 345, 'max_depth': 5, 'learning_rate': 0.05703754177040862, 'subsample': 0.682572928165223, 'colsample_bytree': 0.739218520660378, 'min_child_weight': 18.45345154020684, 'gamma': 1.2775259819964644, 'reg_alpha': 0.15893817424412593, 'reg_lambda': 4.265575204406147}. Best is trial 2 with value: 0.8370820714994724.

Best trial: 2. Best value: 0.837082:  10%|█         | 4/40 [00:14<02:17,  3.81s/it]

[I 2026-02-24 17:36:55,981] Trial 3 finished with value: 0.8137993792638373 and parameters: {'n_estimators': 371, 'max_depth': 3, 'learning_rate': 0.07890678035150575, 'subsample': 0.6970173863697751, 'colsample_bytree': 0.6771224853008282, 'min_child_weight': 16.64742507586601, 'gamma': 2.5717044088393592, 'reg_alpha': 0.604919156991397, 'reg_lambda': 2.352156484295864}. Best is trial 2 with value: 0.8370820714994724.

Best trial: 2. Best value: 0.837082:  12%|█▎        | 5/40 [00:17<02:04,  3.55s/it]

[I 2026-02-24 17:36:59,083] Trial 4 finished with value: 0.6890469677796713 and parameters: {'n_estimators': 252, 'max_depth': 4, 'learning_rate': 0.014245048347045831, 'subsample': 0.6647504805196646, 'colsample_bytree': 0.6890982310989054, 'min_child_weight': 12.0166141169726, 'gamma': 1.4904201908383756, 'reg_alpha': 0.37632407345710095, 'reg_lambda': 1.9082377563529889}. Best is trial 2 with value: 0.8370820714994724.

Best trial: 5. Best value: 0.845003:  15%|█▌        | 6/40 [00:22<02:19,  4.11s/it]

[I 2026-02-24 17:37:04,272] Trial 5 finished with value: 0.8450034878444107 and parameters: {'n_estimators': 359, 'max_depth': 5, 'learning_rate': 0.09836414199498048, 'subsample': 0.7207020440135431, 'colsample_bytree': 0.621667191225587, 'min_child_weight': 5.2422435522705895, 'gamma': 3.8139415761658744, 'reg_alpha': 0.14577950547734808, 'reg_lambda': 4.452696593735643}. Best is trial 5 with value: 0.8450034878444107.

Best trial: 5. Best value: 0.845003:  18%|█▊        | 7/40 [00:25<02:03,  3.74s/it]

[I 2026-02-24 17:37:07,239] Trial 6 finished with value: 0.7296625525131679 and parameters: {'n_estimators': 248, 'max_depth': 4, 'learning_rate': 0.020193564690777946, 'subsample': 0.6367830653222333, 'colsample_bytree': 0.536402011916066, 'min_child_weight': 16.872838604751376, 'gamma': 0.8127175032757126, 'reg_alpha': 0.7116865760916564, 'reg_lambda': 2.0930417948672395}. Best is trial 5 with value: 0.8450034878444107.

Best trial: 5. Best value: 0.845003:  20%|██        | 8/40 [00:28<01:49,  3.41s/it]

[I 2026-02-24 17:37:09,947] Trial 7 finished with value: 0.6574434843366183 and parameters: {'n_estimators': 209, 'max_depth': 4, 'learning_rate': 0.014184642063522313, 'subsample': 0.741888686859994, 'colsample_bytree': 0.7923205603735937, 'min_child_weight': 13.05705754888187, 'gamma': 1.0406575438039574, 'reg_alpha': 0.34263121720773526, 'reg_lambda': 1.1886410418918536}. Best is trial 5 with value: 0.8450034878444107.

Best trial: 5. Best value: 0.845003:  22%|██▎       | 9/40 [00:32<01:49,  3.52s/it]

[I 2026-02-24 17:37:13,705] Trial 8 finished with value: 0.8323348616618989 and parameters: {'n_estimators': 262, 'max_depth': 5, 'learning_rate': 0.051552802260078114, 'subsample': 0.7038485846042348, 'colsample_bytree': 0.6682136948341961, 'min_child_weight': 11.189512497358345, 'gamma': 1.7263396448172752, 'reg_alpha': 0.22818909590603298, 'reg_lambda': 3.4843321393593207}. Best is trial 5 with value: 0.8450034878444107.

Best trial: 5. Best value: 0.845003:  25%|██▌       | 10/40 [00:35<01:41,  3.38s/it]

[I 2026-02-24 17:37:16,780] Trial 9 finished with value: 0.7537077395973611 and parameters: {'n_estimators': 254, 'max_depth': 4, 'learning_rate': 0.02447369267119838, 'subsample': 0.7521945114887375, 'colsample_bytree': 0.7010170699819899, 'min_child_weight': 19.14740829254432, 'gamma': 4.229230314038075, 'reg_alpha': 0.2552498811207111, 'reg_lambda': 4.534090546394603}. Best is trial 5 with value: 0.8450034878444107.

Best trial: 5. Best value: 0.845003:  28%|██▊       | 11/40 [00:39<01:47,  3.72s/it]

[I 2026-02-24 17:37:21,268] Trial 10 finished with value: 0.8417051583175639 and parameters: {'n_estimators': 319, 'max_depth': 5, 'learning_rate': 0.08319261195834518, 'subsample': 0.5515300085848549, 'colsample_bytree': 0.6090530077257266, 'min_child_weight': 5.139416939718863, 'gamma': 4.879285910434986, 'reg_alpha': 0.9963462583054805, 'reg_lambda': 4.9852150620747135}. Best is trial 5 with value: 0.8450034878444107.

Best trial: 5. Best value: 0.845003:  30%|███       | 12/40 [00:44<01:54,  4.08s/it]

[I 2026-02-24 17:37:26,170] Trial 11 finished with value: 0.8419861188956119 and parameters: {'n_estimators': 321, 'max_depth': 5, 'learning_rate': 0.0956320846194035, 'subsample': 0.5432141389614308, 'colsample_bytree': 0.5996143999700388, 'min_child_weight': 5.133905193389047, 'gamma': 4.982287443249351, 'reg_alpha': 0.04642564977970509, 'reg_lambda': 4.982181258373875}. Best is trial 5 with value: 0.8450034878444107.

Best trial: 5. Best value: 0.845003:  32%|███▎      | 13/40 [00:50<02:03,  4.58s/it]

[I 2026-02-24 17:37:31,911] Trial 12 finished with value: 0.8430949957074588 and parameters: {'n_estimators': 395, 'max_depth': 5, 'learning_rate': 0.09199204529353502, 'subsample': 0.5410188059029513, 'colsample_bytree': 0.6130468579769413, 'min_child_weight': 8.262421748830377, 'gamma': 3.56765004034228, 'reg_alpha': 7.343521339639447e-05, 'reg_lambda': 3.937031343391361}. Best is trial 5 with value: 0.8450034878444107.

Best trial: 5. Best value: 0.845003:  35%|███▌      | 14/40 [00:56<02:09,  5.00s/it]

[I 2026-02-24 17:37:37,867] Trial 13 finished with value: 0.8402016403444715 and parameters: {'n_estimators': 399, 'max_depth': 5, 'learning_rate': 0.05994000651985265, 'subsample': 0.5948545606361596, 'colsample_bytree': 0.5034463792531589, 'min_child_weight': 8.774397972962516, 'gamma': 3.31968139840029, 'reg_alpha': 0.0351946740976765, 'reg_lambda': 3.8286083972864415}. Best is trial 5 with value: 0.8450034878444107.

Best trial: 5. Best value: 0.845003:  38%|███▊      | 15/40 [01:00<01:55,  4.61s/it]

[I 2026-02-24 17:37:41,576] Trial 14 finished with value: 0.7719280780899551 and parameters: {'n_estimators': 388, 'max_depth': 3, 'learning_rate': 0.03522572441739252, 'subsample': 0.516348453947652, 'colsample_bytree': 0.6201181302821268, 'min_child_weight': 8.434390456404422, 'gamma': 3.16150169245838, 'reg_alpha': 0.005548806941992668, 'reg_lambda': 3.689997839499389}. Best is trial 5 with value: 0.8450034878444107.

Best trial: 5. Best value: 0.845003:  40%|████      | 16/40 [01:05<01:55,  4.82s/it]

[I 2026-02-24 17:37:46,874] Trial 15 finished with value: 0.8438313352464506 and parameters: {'n_estimators': 361, 'max_depth': 5, 'learning_rate': 0.09948010857120698, 'subsample': 0.6152675696562688, 'colsample_bytree': 0.6372356702780541, 'min_child_weight': 8.032640411836041, 'gamma': 3.8745558558595685, 'reg_alpha': 0.15705501877180014, 'reg_lambda': 2.7381225208058284}. Best is trial 5 with value: 0.8450034878444107.

Best trial: 5. Best value: 0.845003:  42%|████▎     | 17/40 [01:10<01:53,  4.94s/it]

[I 2026-02-24 17:37:52,100] Trial 16 finished with value: 0.8374586618881669 and parameters: {'n_estimators': 355, 'max_depth': 5, 'learning_rate': 0.049595669645650965, 'subsample': 0.6274968933793157, 'colsample_bytree': 0.6433209148404924, 'min_child_weight': 10.184173178518382, 'gamma': 2.593771472486149, 'reg_alpha': 0.16311976572607395, 'reg_lambda': 2.692566902327457}. Best is trial 5 with value: 0.8450034878444107.

Best trial: 5. Best value: 0.845003:  45%|████▌     | 18/40 [01:14<01:42,  4.66s/it]

[I 2026-02-24 17:37:56,096] Trial 17 finished with value: 0.8381010792902428 and parameters: {'n_estimators': 294, 'max_depth': 5, 'learning_rate': 0.06406640127988567, 'subsample': 0.5849284610062654, 'colsample_bytree': 0.7406709223138518, 'min_child_weight': 7.004692154309415, 'gamma': 4.3292233377391725, 'reg_alpha': 0.5217922723945518, 'reg_lambda': 3.0155327006271033}. Best is trial 5 with value: 0.8450034878444107.

Best trial: 5. Best value: 0.845003:  48%|████▊     | 19/40 [01:18<01:30,  4.30s/it]

[I 2026-02-24 17:37:59,573] Trial 18 finished with value: 0.7778650856199084 and parameters: {'n_estimators': 339, 'max_depth': 3, 'learning_rate': 0.043453672003109296, 'subsample': 0.7395439604245044, 'colsample_bytree': 0.6445484917965303, 'min_child_weight': 14.039640495553959, 'gamma': 2.914464209392244, 'reg_alpha': 0.8732399951703287, 'reg_lambda': 1.3497001376563593}. Best is trial 5 with value: 0.8450034878444107.

Best trial: 5. Best value: 0.845003:  50%|█████     | 20/40 [01:22<01:26,  4.31s/it]

[I 2026-02-24 17:38:03,917] Trial 19 finished with value: 0.8396228703649479 and parameters: {'n_estimators': 294, 'max_depth': 5, 'learning_rate': 0.07543717797324856, 'subsample': 0.6080401261905057, 'colsample_bytree': 0.5665965833665653, 'min_child_weight': 10.046973227906753, 'gamma': 3.7636878616381586, 'reg_alpha': 0.32271824450868924, 'reg_lambda': 2.6178788175822394}. Best is trial 5 with value: 0.8450034878444107.

Best trial: 5. Best value: 0.845003:  52%|█████▎    | 21/40 [01:26<01:20,  4.23s/it]

[I 2026-02-24 17:38:07,933] Trial 20 finished with value: 0.8365683645369453 and parameters: {'n_estimators': 318, 'max_depth': 4, 'learning_rate': 0.09959439631662872, 'subsample': 0.7902284412165644, 'colsample_bytree': 0.7157385860871377, 'min_child_weight': 6.78493736710118, 'gamma': 4.304288825695279, 'reg_alpha': 0.14972859969150631, 'reg_lambda': 3.3887180287175758}. Best is trial 5 with value: 0.8450034878444107.

Best trial: 5. Best value: 0.845003:  55%|█████▌    | 22/40 [01:31<01:21,  4.55s/it]

[I 2026-02-24 17:38:13,241] Trial 21 finished with value: 0.8406782877739808 and parameters: {'n_estimators': 373, 'max_depth': 5, 'learning_rate': 0.07320209482719905, 'subsample': 0.5619347436556914, 'colsample_bytree': 0.6247952010665785, 'min_child_weight': 8.443910991482714, 'gamma': 3.4557523982120615, 'reg_alpha': 0.10187657884293871, 'reg_lambda': 4.028537208105742}. Best is trial 5 with value: 0.8450034878444107.

Best trial: 5. Best value: 0.845003:  57%|█████▊    | 23/40 [01:37<01:22,  4.84s/it]

[I 2026-02-24 17:38:18,764] Trial 22 finished with value: 0.8436031358441081 and parameters: {'n_estimators': 372, 'max_depth': 5, 'learning_rate': 0.099447813356778, 'subsample': 0.5007133328248039, 'colsample_bytree': 0.591121468555875, 'min_child_weight': 7.473911375366837, 'gamma': 3.880134995523049, 'reg_alpha': 0.2571725916726542, 'reg_lambda': 4.654986503769341}. Best is trial 5 with value: 0.8450034878444107.

Best trial: 5. Best value: 0.845003:  60%|██████    | 24/40 [01:42<01:19,  4.98s/it]

[I 2026-02-24 17:38:24,054] Trial 23 finished with value: 0.8410816881462712 and parameters: {'n_estimators': 366, 'max_depth': 5, 'learning_rate': 0.06774126970478708, 'subsample': 0.5055155494611713, 'colsample_bytree': 0.5801486001411984, 'min_child_weight': 6.162679602281204, 'gamma': 4.557455926103741, 'reg_alpha': 0.24962885613043653, 'reg_lambda': 4.729352337056454}. Best is trial 5 with value: 0.8450034878444107.

Best trial: 5. Best value: 0.845003:  62%|██████▎   | 25/40 [01:47<01:14,  4.95s/it]

[I 2026-02-24 17:38:28,928] Trial 24 finished with value: 0.8331253109932277 and parameters: {'n_estimators': 335, 'max_depth': 5, 'learning_rate': 0.042523456396325925, 'subsample': 0.7157402510615942, 'colsample_bytree': 0.5373939814858494, 'min_child_weight': 9.88931320267158, 'gamma': 3.9566687038455877, 'reg_alpha': 0.45386216892549297, 'reg_lambda': 4.56625914227091}. Best is trial 5 with value: 0.8450034878444107.

Best trial: 5. Best value: 0.845003:  65%|██████▌   | 26/40 [01:52<01:11,  5.11s/it]

[I 2026-02-24 17:38:34,438] Trial 25 finished with value: 0.8437186047675486 and parameters: {'n_estimators': 383, 'max_depth': 5, 'learning_rate': 0.09856189352064595, 'subsample': 0.6499789429206695, 'colsample_bytree': 0.5929595319736489, 'min_child_weight': 7.572349486378831, 'gamma': 2.3196082641356477, 'reg_alpha': 0.22786404269153565, 'reg_lambda': 1.848581529031263}. Best is trial 5 with value: 0.8450034878444107.

Best trial: 5. Best value: 0.845003:  68%|██████▊   | 27/40 [01:58<01:09,  5.33s/it]

[I 2026-02-24 17:38:40,254] Trial 26 finished with value: 0.8449219174527627 and parameters: {'n_estimators': 382, 'max_depth': 5, 'learning_rate': 0.0818148846697702, 'subsample': 0.6540511759744756, 'colsample_bytree': 0.6577612018672669, 'min_child_weight': 5.735384944642111, 'gamma': 2.0455392370204564, 'reg_alpha': 0.1044245740013679, 'reg_lambda': 1.5640947574199935}. Best is trial 5 with value: 0.8450034878444107.

Best trial: 5. Best value: 0.845003:  70%|███████   | 28/40 [02:03<01:01,  5.10s/it]

[I 2026-02-24 17:38:44,827] Trial 27 finished with value: 0.6952635583847194 and parameters: {'n_estimators': 353, 'max_depth': 4, 'learning_rate': 0.010413185535760545, 'subsample': 0.6364173836966855, 'colsample_bytree': 0.6567576732201269, 'min_child_weight': 5.704043184268218, 'gamma': 2.9951844403533463, 'reg_alpha': 0.08779804539830585, 'reg_lambda': 1.5015105849648154}. Best is trial 5 with value: 0.8450034878444107.

Best trial: 28. Best value: 0.846746:  72%|███████▎  | 29/40 [02:08<00:56,  5.13s/it]

[I 2026-02-24 17:38:50,042] Trial 28 finished with value: 0.8467457822808854 and parameters: {'n_estimators': 357, 'max_depth': 5, 'learning_rate': 0.08249122310654389, 'subsample': 0.7627569037438534, 'colsample_bytree': 0.6371781856989825, 'min_child_weight': 5.064480501276122, 'gamma': 2.224033649170142, 'reg_alpha': 0.1197130970552909, 'reg_lambda': 1.0323906587708742}. Best is trial 28 with value: 0.8467457822808854.

Best trial: 28. Best value: 0.846746:  75%|███████▌  | 30/40 [02:12<00:46,  4.68s/it]

[I 2026-02-24 17:38:53,659] Trial 29 finished with value: 0.8329245757651836 and parameters: {'n_estimators': 307, 'max_depth': 4, 'learning_rate': 0.0827092555177206, 'subsample': 0.7846626791198537, 'colsample_bytree': 0.7255547659016354, 'min_child_weight': 14.961710332525517, 'gamma': 2.058431214964224, 'reg_alpha': 0.4075903845144184, 'reg_lambda': 1.0886627951050305}. Best is trial 28 with value: 0.8467457822808854.

Best trial: 28. Best value: 0.846746:  78%|███████▊  | 31/40 [02:16<00:40,  4.51s/it]

[I 2026-02-24 17:38:57,768] Trial 30 finished with value: 0.8413843514595227 and parameters: {'n_estimators': 279, 'max_depth': 5, 'learning_rate': 0.06615547755588826, 'subsample': 0.7709532791645811, 'colsample_bytree': 0.6700473468235008, 'min_child_weight': 5.984617157050051, 'gamma': 2.1868783420792273, 'reg_alpha': 0.30910150356987803, 'reg_lambda': 1.6115261882712206}. Best is trial 28 with value: 0.8467457822808854.

Best trial: 28. Best value: 0.846746:  80%|████████  | 32/40 [02:21<00:38,  4.82s/it]

[I 2026-02-24 17:39:03,309] Trial 31 finished with value: 0.844636330078625 and parameters: {'n_estimators': 358, 'max_depth': 5, 'learning_rate': 0.08106925529061892, 'subsample': 0.7231075536465761, 'colsample_bytree': 0.6383206014588194, 'min_child_weight': 5.050740417752366, 'gamma': 1.713025421891246, 'reg_alpha': 0.10908168632591053, 'reg_lambda': 2.684895760575506}. Best is trial 28 with value: 0.8467457822808854.

Best trial: 28. Best value: 0.846746:  82%|████████▎ | 33/40 [02:27<00:35,  5.09s/it]

[I 2026-02-24 17:39:09,033] Trial 32 finished with value: 0.845695740586919 and parameters: {'n_estimators': 383, 'max_depth': 5, 'learning_rate': 0.08176131778602322, 'subsample': 0.7261217269761115, 'colsample_bytree': 0.6283849501011535, 'min_child_weight': 5.00334669636528, 'gamma': 1.858358397138765, 'reg_alpha': 0.0792203093088948, 'reg_lambda': 2.2971546779654224}. Best is trial 28 with value: 0.8467457822808854.

Best trial: 28. Best value: 0.846746:  85%|████████▌ | 34/40 [02:33<00:31,  5.28s/it]

[I 2026-02-24 17:39:14,742] Trial 33 finished with value: 0.8430868868363799 and parameters: {'n_estimators': 381, 'max_depth': 5, 'learning_rate': 0.055203527823059706, 'subsample': 0.7721037227531609, 'colsample_bytree': 0.6584507892134401, 'min_child_weight': 6.549591444333836, 'gamma': 2.3608249110393333, 'reg_alpha': 0.07698808607410944, 'reg_lambda': 2.271728960441508}. Best is trial 28 with value: 0.8467457822808854.

Best trial: 28. Best value: 0.846746:  88%|████████▊ | 35/40 [02:38<00:26,  5.23s/it]

[I 2026-02-24 17:39:19,874] Trial 34 finished with value: 0.8377272587711733 and parameters: {'n_estimators': 345, 'max_depth': 5, 'learning_rate': 0.04465088381597381, 'subsample': 0.6806445507411323, 'colsample_bytree': 0.6865176205134823, 'min_child_weight': 5.980396264297109, 'gamma': 1.8501265077341402, 'reg_alpha': 0.19460770709071962, 'reg_lambda': 1.6866763806327254}. Best is trial 28 with value: 0.8467457822808854.

Best trial: 28. Best value: 0.846746:  90%|█████████ | 36/40 [02:44<00:21,  5.37s/it]

[I 2026-02-24 17:39:25,575] Trial 35 finished with value: 0.8438864411248559 and parameters: {'n_estimators': 400, 'max_depth': 5, 'learning_rate': 0.07302719538403618, 'subsample': 0.7551617194166987, 'colsample_bytree': 0.5512283556303343, 'min_child_weight': 9.21974814574611, 'gamma': 1.3702352257934396, 'reg_alpha': 0.1363949095268028, 'reg_lambda': 1.331410260283142}. Best is trial 28 with value: 0.8467457822808854.

Best trial: 28. Best value: 0.846746:  92%|█████████▎| 37/40 [02:48<00:15,  5.03s/it]

[I 2026-02-24 17:39:29,811] Trial 36 finished with value: 0.78464368804878 and parameters: {'n_estimators': 334, 'max_depth': 4, 'learning_rate': 0.024324662009834817, 'subsample': 0.6634453895756615, 'colsample_bytree': 0.6304834558330693, 'min_child_weight': 7.092975475370169, 'gamma': 2.5928261675842044, 'reg_alpha': 0.5666389148677105, 'reg_lambda': 1.0033539693691333}. Best is trial 28 with value: 0.8467457822808854.

Best trial: 28. Best value: 0.846746:  95%|█████████▌| 38/40 [02:53<00:10,  5.22s/it]

[I 2026-02-24 17:39:35,462] Trial 37 finished with value: 0.8457763875692402 and parameters: {'n_estimators': 377, 'max_depth': 5, 'learning_rate': 0.08545202367068216, 'subsample': 0.6984144340622281, 'colsample_bytree': 0.692328826606052, 'min_child_weight': 5.603908871588197, 'gamma': 0.7418579566597399, 'reg_alpha': 0.667458519197389, 'reg_lambda': 2.024276829735383}. Best is trial 28 with value: 0.8467457822808854.

Best trial: 28. Best value: 0.846746:  98%|█████████▊| 39/40 [02:58<00:05,  5.07s/it]

[I 2026-02-24 17:39:40,199] Trial 38 finished with value: 0.8304833091066275 and parameters: {'n_estimators': 375, 'max_depth': 4, 'learning_rate': 0.05948736966777268, 'subsample': 0.700523290199027, 'colsample_bytree': 0.75668857054051, 'min_child_weight': 11.127608668689774, 'gamma': 0.5581576015632619, 'reg_alpha': 0.7121563059574163, 'reg_lambda': 2.1785338875622475}. Best is trial 28 with value: 0.8467457822808854.

Best trial: 28. Best value: 0.846746: 100%|██████████| 40/40 [03:03<00:00,  4.58s/it]

[I 2026-02-24 17:39:44,684] Trial 39 finished with value: 0.7966377666182813 and parameters: {'n_estimators': 349, 'max_depth': 4, 'learning_rate': 0.02879765499416988, 'subsample': 0.727110223037551, 'colsample_bytree': 0.6968362884328384, 'min_child_weight': 17.69639927763636, 'gamma': 1.1234381238365312, 'reg_alpha': 0.804271446985044, 'reg_lambda': 2.443888029663171}. Best is trial 28 with value: 0.8467457822808854.
Best CV R²: 0.8467457822808854
Best params:
  n_estimators: 357
  max_depth: 5
  learning_rate: 0.08249122310654389
  subsample: 0.7627569037438534
  colsample_bytree: 0.6371781856989825
  min_child_weight: 5.064480501276122
  gamma: 2.224033649170142
  reg_alpha: 0.1197130970552909
  reg_lambda: 1.0323906587708742

In [15]:
# Train final model with best hyperparameters and report R² + feature importances

best_params = study.best_params.copy()
best_params.update({"random_state": 42, "n_jobs": -1})

final_model = xgb.XGBRegressor(**best_params)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

final_model.fit(
    X_train,
    y_train,
    eval_set=[(X_test, y_test)],
    verbose=False,
)

y_train_pred = final_model.predict(X_train)
y_test_pred = final_model.predict(X_test)

r2_train = r2_score(y_train, y_train_pred)
r2_test = r2_score(y_test, y_test_pred)

print(f"Final model (with tuned params) Train R²: {r2_train:.3f}")
print(f"Final model (with tuned params) Test  R²: {r2_test:.3f}")

# Feature importances from tuned model
importances = final_model.feature_importances_
fi_tuned = pd.DataFrame({"feature": feature_cols, "importance": importances})
fi_tuned = fi_tuned.sort_values("importance", ascending=False)

print("\nTop 20 most important features for predicting EC (tuned model):")
print(fi_tuned.head(40).to_string(index=False))

fi_tuned.head(40)

Final model (with tuned params) Train R²: 0.917
Final model (with tuned params) Test  R²: 0.853

Top 20 most important features for predicting EC (tuned model):
                   feature  importance
        esa_water_frac_1km    0.086473
      esa_flooded_frac_1km    0.074073
                water_perm    0.062950
            esa_lccs_class    0.056473
          recurrence_ratio    0.055568
        esa_other_frac_1km    0.053473
       esa_forest_frac_1km    0.051392
   gsw_occurrence_mean_1km    0.050728
        esa_urban_frac_1km    0.050115
        esa_shrub_frac_1km    0.042791
   gsw_recurrence_mean_1km    0.042771
                      soil    0.042761
        esa_grass_frac_1km    0.041515
   esa_sparse_veg_frac_1km    0.040188
          esa_change_count    0.039968
    gaia_changed_ever_frac    0.037143
     esa_cropland_frac_1km    0.032911
gaia_changed_ever_frac_1km    0.028672
      gsw_occ_x_impervious    0.024569
           gsw_transitions    0.022804
                gsw_change    0.015075
                       vpd    0.010929
          eci_x_impervious    0.010662
                       vap    0.010451
                       def    0.009695
           wb_x_impervious    0.005850

                       feature  importance
9           esa_water_frac_1km    0.086473
0         esa_flooded_frac_1km    0.074073
4                   water_perm    0.062950
8               esa_lccs_class    0.056473
5             recurrence_ratio    0.055568
7           esa_other_frac_1km    0.053473
2          esa_forest_frac_1km    0.051392
10     gsw_occurrence_mean_1km    0.050728
16          esa_urban_frac_1km    0.050115
15          esa_shrub_frac_1km    0.042791
6      gsw_recurrence_mean_1km    0.042771
11                        soil    0.042761
3           esa_grass_frac_1km    0.041515
1      esa_sparse_veg_frac_1km    0.040188
14            esa_change_count    0.039968
23      gaia_changed_ever_frac    0.037143
17       esa_cropland_frac_1km    0.032911
13  gaia_changed_ever_frac_1km    0.028672
18        gsw_occ_x_impervious    0.024569
12             gsw_transitions    0.022804
25                  gsw_change    0.015075
20                         vpd    0.010929
24            eci_x_impervious    0.010662
19                         vap    0.010451
21                         def    0.009695
22             wb_x_impervious    0.005850

In [16]:
# Create submission1.csv: predictions for EC on the 202 validation rows

# Load submission template (IDs and column order)
sub_template = pd.read_csv("../submission_template.csv")

# Load engineered validation features
val_features = pd.read_csv("../New Datasets/Combined/combined_validation_engineered.csv")

# Standardize keys in template to match engineered features
sub_std = sub_template.rename(columns={
    "Latitude": "latitude",
    "Longitude": "longitude",
    "Sample Date": "sample_date",
})

# Join validation features with template IDs
val_full = val_features.merge(
    sub_std[["latitude", "longitude", "sample_date"]],
    on=["latitude", "longitude", "sample_date"],
    how="inner",
)

print("Validation engineered shape:", val_features.shape)
print("Validation rows with matched features:", val_full.shape[0])

# Build X for validation using the same selected feature set as training
X_val = val_full[feature_cols].copy()

# Predict EC for validation rows
ec_pred = final_model.predict(X_val)

# Build prediction frame with original column names
pred_df = val_full[["latitude", "longitude", "sample_date"]].copy()
pred_df["Electrical Conductance"] = ec_pred
pred_df = pred_df.rename(columns={
    "latitude": "Latitude",
    "longitude": "Longitude",
    "sample_date": "Sample Date",
})

# Start from template and overwrite EC with predictions
submission1 = sub_template.copy()
submission1 = submission1.drop(columns=["Electrical Conductance"]).merge(
    pred_df,
    on=["Latitude", "Longitude", "Sample Date"],
    how="left",
)

out_path = "../submission1.csv"
submission1.to_csv(out_path, index=False)
print("Saved:", out_path)
submission1.head()

Validation engineered shape: (200, 82)
Validation rows with matched features: 200
Saved: ../submission1.csv

,Latitude,Longitude,Sample Date,Total Alkalinity,Dissolved Reactive Phosphorus,Electrical Conductance
0,-32.043333,27.822778,01-09-2014,NaN,NaN,469.420074
1,-33.329167,26.077500,16-09-2015,NaN,NaN,161.709778
2,-32.991639,27.640028,07-05-2015,NaN,NaN,221.352066
3,-34.096389,24.439167,07-02-2012,NaN,NaN,343.663879
4,-32.000556,28.581667,01-10-2014,NaN,NaN,530.699402